package meter

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/evcc-io/evcc/api"
)

func decorateBoschBpts5Hybrid(base api.Meter, battery func() (float64, error), batteryCapacity func() float64, batteryPowerLimiter func() (float64, float64)) api.Meter {
	switch {
	case battery == nil:
		return base

	case battery != nil && batteryCapacity == nil && batteryPowerLimiter == nil:
		return &struct {
			api.Meter
			api.Battery
		}{
			Meter: base,
			Battery: &decorateBoschBpts5HybridBatteryImpl{
				battery: battery,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryPowerLimiter == nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryCapacity
		}{
			Meter: base,
			Battery: &decorateBoschBpts5HybridBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decorateBoschBpts5HybridBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryPowerLimiter != nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryPowerLimiter
		}{
			Meter: base,
			Battery: &decorateBoschBpts5HybridBatteryImpl{
				battery: battery,
			},
			BatteryPowerLimiter: &decorateBoschBpts5HybridBatteryPowerLimiterImpl{
				batteryPowerLimiter: batteryPowerLimiter,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryPowerLimiter != nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryCapacity
			api.BatteryPowerLimiter
		}{
			Meter: base,
			Battery: &decorateBoschBpts5HybridBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decorateBoschBpts5HybridBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			BatteryPowerLimiter: &decorateBoschBpts5HybridBatteryPowerLimiterImpl{
				batteryPowerLimiter: batteryPowerLimiter,
			},
		}
	}

	return nil
}

type decorateBoschBpts5HybridBatteryImpl struct {
	battery func() (float64, error)
}

func (impl *decorateBoschBpts5HybridBatteryImpl) Soc() (float64, error) {
	return impl.battery()
}

type decorateBoschBpts5HybridBatteryCapacityImpl struct {
	batteryCapacity func() float64
}

func (impl *decorateBoschBpts5HybridBatteryCapacityImpl) Capacity() float64 {
	return impl.batteryCapacity()
}

type decorateBoschBpts5HybridBatteryPowerLimiterImpl struct {
	batteryPowerLimiter func() (float64, float64)
}

func (impl *decorateBoschBpts5HybridBatteryPowerLimiterImpl) GetPowerLimits() (float64, float64) {
	return impl.batteryPowerLimiter()
}
