package meter

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/evcc-io/evcc/api"
)

func decorateGoodWeWifi(base *goodWeWiFiMeter, battery func() (float64, error)) api.Meter {
	switch {
	case battery == nil:
		return base

	case battery != nil:
		return &struct {
			*goodWeWiFiMeter
			api.Battery
		}{
			goodWeWiFiMeter: base,
			Battery: &decorateGoodWeWifiBatteryImpl{
				battery: battery,
			},
		}
	}

	return nil
}

type decorateGoodWeWifiBatteryImpl struct {
	battery func() (float64, error)
}

func (impl *decorateGoodWeWifiBatteryImpl) Soc() (float64, error) {
	return impl.battery()
}
