package meter

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"reflect"

	"github.com/evcc-io/evcc/api"
	"github.com/evcc-io/evcc/api/implement"
)

func decorateGoodWeWifi(base *goodWeWiFi, battery func() (float64, error), batteryCapacity func() float64) api.Meter {
	caps := make(map[reflect.Type]any)

	if battery != nil {
		caps[reflect.TypeFor[api.Battery]()] = implement.Battery(battery)
	}

	if batteryCapacity != nil {
		caps[reflect.TypeFor[api.BatteryCapacity]()] = implement.BatteryCapacity(batteryCapacity)
	}

	if len(caps) == 0 {
		return base
	}

	return &decorateGoodWeWifiCapable{goodWeWiFi: base, caps: caps}
}

type decorateGoodWeWifiCapable struct {
	*goodWeWiFi
	caps map[reflect.Type]any
}

func (d *decorateGoodWeWifiCapable) Capability(typ reflect.Type) (any, bool) {
	c, ok := d.caps[typ]
	if !ok && reflect.TypeOf(d).Implements(typ) {
		return d, true
	}
	return c, ok
}
