package meter

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/evcc-io/evcc/api"
)

func decorateModbus(base api.Meter, meterEnergy func() (float64, error), meterCurrent func() (float64, float64, float64, error), meterVoltage func() (float64, float64, float64, error), meterPower func() (float64, float64, float64, error), battery func() (float64, error), batteryCapacity func() float64) api.Meter {
	switch {
	case battery == nil && batteryCapacity == nil && meterCurrent == nil && meterEnergy == nil && meterPower == nil && meterVoltage == nil:
		return base

	case battery == nil && batteryCapacity == nil && meterCurrent == nil && meterEnergy != nil && meterPower == nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.MeterEnergy
		}{
			Meter: base,
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery == nil && batteryCapacity == nil && meterCurrent != nil && meterEnergy == nil && meterPower == nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.MeterCurrent
		}{
			Meter: base,
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
		}

	case battery == nil && batteryCapacity == nil && meterCurrent != nil && meterEnergy != nil && meterPower == nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.MeterCurrent
			api.MeterEnergy
		}{
			Meter: base,
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery == nil && batteryCapacity == nil && meterCurrent == nil && meterEnergy == nil && meterPower == nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.MeterVoltage
		}{
			Meter: base,
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery == nil && batteryCapacity == nil && meterCurrent == nil && meterEnergy != nil && meterPower == nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.MeterEnergy
			api.MeterVoltage
		}{
			Meter: base,
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery == nil && batteryCapacity == nil && meterCurrent != nil && meterEnergy == nil && meterPower == nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.MeterCurrent
			api.MeterVoltage
		}{
			Meter: base,
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery == nil && batteryCapacity == nil && meterCurrent != nil && meterEnergy != nil && meterPower == nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.MeterCurrent
			api.MeterEnergy
			api.MeterVoltage
		}{
			Meter: base,
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery == nil && batteryCapacity == nil && meterCurrent == nil && meterEnergy == nil && meterPower != nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.MeterPower
		}{
			Meter: base,
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
		}

	case battery == nil && batteryCapacity == nil && meterCurrent == nil && meterEnergy != nil && meterPower != nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.MeterEnergy
			api.MeterPower
		}{
			Meter: base,
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
		}

	case battery == nil && batteryCapacity == nil && meterCurrent != nil && meterEnergy == nil && meterPower != nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.MeterCurrent
			api.MeterPower
		}{
			Meter: base,
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
		}

	case battery == nil && batteryCapacity == nil && meterCurrent != nil && meterEnergy != nil && meterPower != nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.MeterCurrent
			api.MeterEnergy
			api.MeterPower
		}{
			Meter: base,
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
		}

	case battery == nil && batteryCapacity == nil && meterCurrent == nil && meterEnergy == nil && meterPower != nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.MeterPower
			api.MeterVoltage
		}{
			Meter: base,
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery == nil && batteryCapacity == nil && meterCurrent == nil && meterEnergy != nil && meterPower != nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.MeterEnergy
			api.MeterPower
			api.MeterVoltage
		}{
			Meter: base,
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery == nil && batteryCapacity == nil && meterCurrent != nil && meterEnergy == nil && meterPower != nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.MeterCurrent
			api.MeterPower
			api.MeterVoltage
		}{
			Meter: base,
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery == nil && batteryCapacity == nil && meterCurrent != nil && meterEnergy != nil && meterPower != nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.MeterCurrent
			api.MeterEnergy
			api.MeterPower
			api.MeterVoltage
		}{
			Meter: base,
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery != nil && batteryCapacity == nil && meterCurrent == nil && meterEnergy == nil && meterPower == nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.Battery
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
		}

	case battery != nil && batteryCapacity == nil && meterCurrent == nil && meterEnergy != nil && meterPower == nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.Battery
			api.MeterEnergy
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity == nil && meterCurrent != nil && meterEnergy == nil && meterPower == nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.Battery
			api.MeterCurrent
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
		}

	case battery != nil && batteryCapacity == nil && meterCurrent != nil && meterEnergy != nil && meterPower == nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.Battery
			api.MeterCurrent
			api.MeterEnergy
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity == nil && meterCurrent == nil && meterEnergy == nil && meterPower == nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.Battery
			api.MeterVoltage
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery != nil && batteryCapacity == nil && meterCurrent == nil && meterEnergy != nil && meterPower == nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.Battery
			api.MeterEnergy
			api.MeterVoltage
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery != nil && batteryCapacity == nil && meterCurrent != nil && meterEnergy == nil && meterPower == nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.Battery
			api.MeterCurrent
			api.MeterVoltage
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery != nil && batteryCapacity == nil && meterCurrent != nil && meterEnergy != nil && meterPower == nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.Battery
			api.MeterCurrent
			api.MeterEnergy
			api.MeterVoltage
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery != nil && batteryCapacity == nil && meterCurrent == nil && meterEnergy == nil && meterPower != nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.Battery
			api.MeterPower
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
		}

	case battery != nil && batteryCapacity == nil && meterCurrent == nil && meterEnergy != nil && meterPower != nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.Battery
			api.MeterEnergy
			api.MeterPower
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
		}

	case battery != nil && batteryCapacity == nil && meterCurrent != nil && meterEnergy == nil && meterPower != nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.Battery
			api.MeterCurrent
			api.MeterPower
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
		}

	case battery != nil && batteryCapacity == nil && meterCurrent != nil && meterEnergy != nil && meterPower != nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.Battery
			api.MeterCurrent
			api.MeterEnergy
			api.MeterPower
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
		}

	case battery != nil && batteryCapacity == nil && meterCurrent == nil && meterEnergy == nil && meterPower != nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.Battery
			api.MeterPower
			api.MeterVoltage
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery != nil && batteryCapacity == nil && meterCurrent == nil && meterEnergy != nil && meterPower != nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.Battery
			api.MeterEnergy
			api.MeterPower
			api.MeterVoltage
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery != nil && batteryCapacity == nil && meterCurrent != nil && meterEnergy == nil && meterPower != nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.Battery
			api.MeterCurrent
			api.MeterPower
			api.MeterVoltage
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery != nil && batteryCapacity == nil && meterCurrent != nil && meterEnergy != nil && meterPower != nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.Battery
			api.MeterCurrent
			api.MeterEnergy
			api.MeterPower
			api.MeterVoltage
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery == nil && batteryCapacity != nil && meterCurrent == nil && meterEnergy == nil && meterPower == nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.BatteryCapacity
		}{
			Meter: base,
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
		}

	case battery == nil && batteryCapacity != nil && meterCurrent == nil && meterEnergy != nil && meterPower == nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.BatteryCapacity
			api.MeterEnergy
		}{
			Meter: base,
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery == nil && batteryCapacity != nil && meterCurrent != nil && meterEnergy == nil && meterPower == nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.BatteryCapacity
			api.MeterCurrent
		}{
			Meter: base,
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
		}

	case battery == nil && batteryCapacity != nil && meterCurrent != nil && meterEnergy != nil && meterPower == nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.BatteryCapacity
			api.MeterCurrent
			api.MeterEnergy
		}{
			Meter: base,
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery == nil && batteryCapacity != nil && meterCurrent == nil && meterEnergy == nil && meterPower == nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.BatteryCapacity
			api.MeterVoltage
		}{
			Meter: base,
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery == nil && batteryCapacity != nil && meterCurrent == nil && meterEnergy != nil && meterPower == nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.BatteryCapacity
			api.MeterEnergy
			api.MeterVoltage
		}{
			Meter: base,
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery == nil && batteryCapacity != nil && meterCurrent != nil && meterEnergy == nil && meterPower == nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.BatteryCapacity
			api.MeterCurrent
			api.MeterVoltage
		}{
			Meter: base,
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery == nil && batteryCapacity != nil && meterCurrent != nil && meterEnergy != nil && meterPower == nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.BatteryCapacity
			api.MeterCurrent
			api.MeterEnergy
			api.MeterVoltage
		}{
			Meter: base,
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery == nil && batteryCapacity != nil && meterCurrent == nil && meterEnergy == nil && meterPower != nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.BatteryCapacity
			api.MeterPower
		}{
			Meter: base,
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
		}

	case battery == nil && batteryCapacity != nil && meterCurrent == nil && meterEnergy != nil && meterPower != nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.BatteryCapacity
			api.MeterEnergy
			api.MeterPower
		}{
			Meter: base,
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
		}

	case battery == nil && batteryCapacity != nil && meterCurrent != nil && meterEnergy == nil && meterPower != nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.BatteryCapacity
			api.MeterCurrent
			api.MeterPower
		}{
			Meter: base,
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
		}

	case battery == nil && batteryCapacity != nil && meterCurrent != nil && meterEnergy != nil && meterPower != nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.BatteryCapacity
			api.MeterCurrent
			api.MeterEnergy
			api.MeterPower
		}{
			Meter: base,
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
		}

	case battery == nil && batteryCapacity != nil && meterCurrent == nil && meterEnergy == nil && meterPower != nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.BatteryCapacity
			api.MeterPower
			api.MeterVoltage
		}{
			Meter: base,
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery == nil && batteryCapacity != nil && meterCurrent == nil && meterEnergy != nil && meterPower != nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.BatteryCapacity
			api.MeterEnergy
			api.MeterPower
			api.MeterVoltage
		}{
			Meter: base,
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery == nil && batteryCapacity != nil && meterCurrent != nil && meterEnergy == nil && meterPower != nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.BatteryCapacity
			api.MeterCurrent
			api.MeterPower
			api.MeterVoltage
		}{
			Meter: base,
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery == nil && batteryCapacity != nil && meterCurrent != nil && meterEnergy != nil && meterPower != nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.BatteryCapacity
			api.MeterCurrent
			api.MeterEnergy
			api.MeterPower
			api.MeterVoltage
		}{
			Meter: base,
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery != nil && batteryCapacity != nil && meterCurrent == nil && meterEnergy == nil && meterPower == nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryCapacity
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
		}

	case battery != nil && batteryCapacity != nil && meterCurrent == nil && meterEnergy != nil && meterPower == nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryCapacity
			api.MeterEnergy
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity != nil && meterCurrent != nil && meterEnergy == nil && meterPower == nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryCapacity
			api.MeterCurrent
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
		}

	case battery != nil && batteryCapacity != nil && meterCurrent != nil && meterEnergy != nil && meterPower == nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryCapacity
			api.MeterCurrent
			api.MeterEnergy
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case battery != nil && batteryCapacity != nil && meterCurrent == nil && meterEnergy == nil && meterPower == nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryCapacity
			api.MeterVoltage
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery != nil && batteryCapacity != nil && meterCurrent == nil && meterEnergy != nil && meterPower == nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryCapacity
			api.MeterEnergy
			api.MeterVoltage
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery != nil && batteryCapacity != nil && meterCurrent != nil && meterEnergy == nil && meterPower == nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryCapacity
			api.MeterCurrent
			api.MeterVoltage
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery != nil && batteryCapacity != nil && meterCurrent != nil && meterEnergy != nil && meterPower == nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryCapacity
			api.MeterCurrent
			api.MeterEnergy
			api.MeterVoltage
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery != nil && batteryCapacity != nil && meterCurrent == nil && meterEnergy == nil && meterPower != nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryCapacity
			api.MeterPower
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
		}

	case battery != nil && batteryCapacity != nil && meterCurrent == nil && meterEnergy != nil && meterPower != nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryCapacity
			api.MeterEnergy
			api.MeterPower
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
		}

	case battery != nil && batteryCapacity != nil && meterCurrent != nil && meterEnergy == nil && meterPower != nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryCapacity
			api.MeterCurrent
			api.MeterPower
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
		}

	case battery != nil && batteryCapacity != nil && meterCurrent != nil && meterEnergy != nil && meterPower != nil && meterVoltage == nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryCapacity
			api.MeterCurrent
			api.MeterEnergy
			api.MeterPower
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
		}

	case battery != nil && batteryCapacity != nil && meterCurrent == nil && meterEnergy == nil && meterPower != nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryCapacity
			api.MeterPower
			api.MeterVoltage
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery != nil && batteryCapacity != nil && meterCurrent == nil && meterEnergy != nil && meterPower != nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryCapacity
			api.MeterEnergy
			api.MeterPower
			api.MeterVoltage
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery != nil && batteryCapacity != nil && meterCurrent != nil && meterEnergy == nil && meterPower != nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryCapacity
			api.MeterCurrent
			api.MeterPower
			api.MeterVoltage
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}

	case battery != nil && batteryCapacity != nil && meterCurrent != nil && meterEnergy != nil && meterPower != nil && meterVoltage != nil:
		return &struct {
			api.Meter
			api.Battery
			api.BatteryCapacity
			api.MeterCurrent
			api.MeterEnergy
			api.MeterPower
			api.MeterVoltage
		}{
			Meter: base,
			Battery: &decorateModbusBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decorateModbusBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			MeterCurrent: &decorateModbusMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateModbusMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			MeterPower: &decorateModbusMeterPowerImpl{
				meterPower: meterPower,
			},
			MeterVoltage: &decorateModbusMeterVoltageImpl{
				meterVoltage: meterVoltage,
			},
		}
	}

	return nil
}

type decorateModbusBatteryImpl struct {
	battery func() (float64, error)
}

func (impl *decorateModbusBatteryImpl) Soc() (float64, error) {
	return impl.battery()
}

type decorateModbusBatteryCapacityImpl struct {
	batteryCapacity func() float64
}

func (impl *decorateModbusBatteryCapacityImpl) Capacity() float64 {
	return impl.batteryCapacity()
}

type decorateModbusMeterCurrentImpl struct {
	meterCurrent func() (float64, float64, float64, error)
}

func (impl *decorateModbusMeterCurrentImpl) Currents() (float64, float64, float64, error) {
	return impl.meterCurrent()
}

type decorateModbusMeterEnergyImpl struct {
	meterEnergy func() (float64, error)
}

func (impl *decorateModbusMeterEnergyImpl) TotalEnergy() (float64, error) {
	return impl.meterEnergy()
}

type decorateModbusMeterPowerImpl struct {
	meterPower func() (float64, float64, float64, error)
}

func (impl *decorateModbusMeterPowerImpl) Powers() (float64, float64, float64, error) {
	return impl.meterPower()
}

type decorateModbusMeterVoltageImpl struct {
	meterVoltage func() (float64, float64, float64, error)
}

func (impl *decorateModbusMeterVoltageImpl) Voltages() (float64, float64, float64, error) {
	return impl.meterVoltage()
}
