package meter

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/evcc-io/evcc/api"
)

func decoratePowerWall(base *PowerWall, energyImport func() (float64, error), battery func() (float64, error), batteryCapacity func() float64, batteryController func(api.BatteryMode) error) api.Meter {
	switch {
	case battery == nil && energyImport == nil:
		return base

	case battery == nil && energyImport != nil:
		return &struct {
			*PowerWall
			api.EnergyImport
		}{
			PowerWall: base,
			EnergyImport: &decoratePowerWallEnergyImportImpl{
				energyImport: energyImport,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController == nil && energyImport == nil:
		return &struct {
			*PowerWall
			api.Battery
		}{
			PowerWall: base,
			Battery: &decoratePowerWallBatteryImpl{
				battery: battery,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController == nil && energyImport != nil:
		return &struct {
			*PowerWall
			api.Battery
			api.EnergyImport
		}{
			PowerWall: base,
			Battery: &decoratePowerWallBatteryImpl{
				battery: battery,
			},
			EnergyImport: &decoratePowerWallEnergyImportImpl{
				energyImport: energyImport,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController == nil && energyImport == nil:
		return &struct {
			*PowerWall
			api.Battery
			api.BatteryCapacity
		}{
			PowerWall: base,
			Battery: &decoratePowerWallBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWallBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController == nil && energyImport != nil:
		return &struct {
			*PowerWall
			api.Battery
			api.BatteryCapacity
			api.EnergyImport
		}{
			PowerWall: base,
			Battery: &decoratePowerWallBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWallBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			EnergyImport: &decoratePowerWallEnergyImportImpl{
				energyImport: energyImport,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController != nil && energyImport == nil:
		return &struct {
			*PowerWall
			api.Battery
			api.BatteryController
		}{
			PowerWall: base,
			Battery: &decoratePowerWallBatteryImpl{
				battery: battery,
			},
			BatteryController: &decoratePowerWallBatteryControllerImpl{
				batteryController: batteryController,
			},
		}

	case battery != nil && batteryCapacity == nil && batteryController != nil && energyImport != nil:
		return &struct {
			*PowerWall
			api.Battery
			api.BatteryController
			api.EnergyImport
		}{
			PowerWall: base,
			Battery: &decoratePowerWallBatteryImpl{
				battery: battery,
			},
			BatteryController: &decoratePowerWallBatteryControllerImpl{
				batteryController: batteryController,
			},
			EnergyImport: &decoratePowerWallEnergyImportImpl{
				energyImport: energyImport,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController != nil && energyImport == nil:
		return &struct {
			*PowerWall
			api.Battery
			api.BatteryCapacity
			api.BatteryController
		}{
			PowerWall: base,
			Battery: &decoratePowerWallBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWallBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			BatteryController: &decoratePowerWallBatteryControllerImpl{
				batteryController: batteryController,
			},
		}

	case battery != nil && batteryCapacity != nil && batteryController != nil && energyImport != nil:
		return &struct {
			*PowerWall
			api.Battery
			api.BatteryCapacity
			api.BatteryController
			api.EnergyImport
		}{
			PowerWall: base,
			Battery: &decoratePowerWallBatteryImpl{
				battery: battery,
			},
			BatteryCapacity: &decoratePowerWallBatteryCapacityImpl{
				batteryCapacity: batteryCapacity,
			},
			BatteryController: &decoratePowerWallBatteryControllerImpl{
				batteryController: batteryController,
			},
			EnergyImport: &decoratePowerWallEnergyImportImpl{
				energyImport: energyImport,
			},
		}
	}

	return nil
}

type decoratePowerWallBatteryImpl struct {
	battery func() (float64, error)
}

func (impl *decoratePowerWallBatteryImpl) Soc() (float64, error) {
	return impl.battery()
}

type decoratePowerWallBatteryCapacityImpl struct {
	batteryCapacity func() float64
}

func (impl *decoratePowerWallBatteryCapacityImpl) Capacity() float64 {
	return impl.batteryCapacity()
}

type decoratePowerWallBatteryControllerImpl struct {
	batteryController func(api.BatteryMode) error
}

func (impl *decoratePowerWallBatteryControllerImpl) SetBatteryMode(p0 api.BatteryMode) error {
	return impl.batteryController(p0)
}

type decoratePowerWallEnergyImportImpl struct {
	energyImport func() (float64, error)
}

func (impl *decoratePowerWallEnergyImportImpl) EnergyImport() (float64, error) {
	return impl.energyImport()
}
