system-prompt: |
  Detect if a GitHub PR comment is written predominantly in a non-English language (especially German).

  Return false if:
  - The comment is very brief (1-5 words)
  - The comment mixes English with technical terms (e.g., "Bundesnetzagentur", "Einspeisevergütung")
  - You are uncertain

prompt: |
  Should this comment be in English?

  {{comment}}

response-format:
  type: json_schema
  json_schema:
    name: language_check
    strict: true
    schema:
      type: object
      properties:
        is_non_english:
          type: boolean
      required:
        - is_non_english
      additionalProperties: false
