version: "2"
run:
  go: "1.24"
linters:
  default: none
  enable:
    - durationcheck
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - unused
    - wastedassign
    - whitespace
  settings:
    staticcheck:
      checks:
        - -SA1019
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
