dist: release
release:
  github:
    owner: evcc-io
    name: evcc
  mode: replace

builds:
  - id: evcc
    main: .
    flags:
      - -trimpath
      - -tags=release
    ldflags:
      - -X github.com/evcc-io/evcc/server.Version={{ .Version }} -X github.com/evcc-io/evcc/vehicle/tesla.TESLA_CLIENT_ID={{ .Env.TESLA_CLIENT_ID }} -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

env:
  - CGO_ENABLED=0

archives:
  - builds:
      - evcc
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - evcc.dist.yaml
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}

universal_binaries:
  - replace: true

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore"
      - "^bump"
      - "^docs:"
      - "^test:"
      - "^Translations"

nfpms:
  - id: default
    package_name: evcc
    file_name_template: "{{ .ConventionalFileName }}"

    homepage: https://evcc.io
    description: EV Charge Controller
    maintainer: andig <cpuidle@gmx.de>
    license: MIT
    vendor: evcc.io

    formats:
      - deb

    contents:
      - src: ./packaging/init/evcc.service
        dst: /lib/systemd/system/evcc.service

    scripts:
      preinstall: ./packaging/scripts/preinstall.sh
      postinstall: ./packaging/scripts/postinstall.sh
      preremove: ./packaging/scripts/preremove.sh
      postremove: ./packaging/scripts/postremove.sh

brews:
  - repository:
      owner: evcc-io
      name: homebrew-tap
    commit_author:
      name: andig
      email: cpuidle@gmx.de
    directory: Formula
    homepage: "https://evcc.io"
    description: "Sonne tanken ☀️🚘"
    license: "MIT"
    test: |
      system "#{bin}/evcc --version"
    service: |
      run [opt_bin/"evcc"]
      working_dir HOMEBREW_PREFIX
      keep_alive true
      log_path var/"log/evcc.log"
      error_log_path var/"log/evcc.log"
