version: 2

dist: release
release:
  disable: true

builds:
  - id: evcc
    main: .
    flags:
      - -trimpath
      - -tags=release
    ldflags:
      - -X github.com/evcc-io/evcc/util.Version={{ .Tag }} -X github.com/evcc-io/evcc/util.Commit={{ .ShortCommit }} -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    overrides:
      - goos: windows
        goarch: amd64
        flags:
          - -trimpath
          - -tags=release,timetzdata

env:
  - CGO_ENABLED=0

archives:
  - ids:
      - evcc
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - evcc.dist.yaml
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}

universal_binaries:
  - replace: true

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: '{{ .Version }}{{ if eq (len (split .Version ".")) 2 }}.0{{ end }}+{{ .Timestamp }}'

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore"
      - "^bump"
      - "^docs:"
      - "^test:"
      - "^build"
      - "^Translations"

nfpms:
  - id: default
    package_name: evcc
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}{{ if .Arm }}hf{{ end }}"

    homepage: https://evcc.io
    description: EV Charge Controller
    maintainer: info@evcc.io
    license: MIT
    vendor: evcc.io

    formats:
      - deb

    dependencies:
      - adduser

    contents:
      - src: ./packaging/init/evcc.service
        dst: /lib/systemd/system/evcc.service

    scripts:
      preinstall: ./packaging/scripts/preinstall.sh
      postinstall: ./packaging/scripts/postinstall.sh
      preremove: ./packaging/scripts/preremove.sh
      postremove: ./packaging/scripts/postremove.sh
