import { defineConfig, lazyPlugins } from "vite-plus";
import vuePlugin from "@vitejs/plugin-vue";
import legacy from "@vitejs/plugin-legacy";
import { browserslistToTargets } from "lightningcss";
import browserslist from "browserslist";
import { visualizer } from "rollup-plugin-visualizer";
import path from "path";

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  lint: {
    plugins: ["oxc", "typescript", "unicorn", "react"],
    categories: {
      correctness: "warn",
    },
    env: {
      builtin: true,
    },
    overrides: [
      {
        files: ["assets/**/*.{ts,js,vue}", "tests/**/*.ts"],
        rules: {
          "constructor-super": "off",
          "for-direction": "error",
          "getter-return": "off",
          "no-async-promise-executor": "error",
          "no-case-declarations": "error",
          "no-class-assign": "off",
          "no-compare-neg-zero": "error",
          "no-cond-assign": "error",
          "no-const-assign": "off",
          "no-constant-binary-expression": "error",
          "no-constant-condition": "error",
          "no-control-regex": "error",
          "no-debugger": "error",
          "no-delete-var": "error",
          "no-dupe-class-members": "off",
          "no-dupe-else-if": "error",
          "no-dupe-keys": "off",
          "no-duplicate-case": "error",
          "no-empty": "error",
          "no-empty-character-class": "error",
          "no-empty-pattern": "error",
          "no-empty-static-block": "error",
          "no-ex-assign": "error",
          "no-extra-boolean-cast": "error",
          "no-fallthrough": "error",
          "no-func-assign": "off",
          "no-global-assign": "error",
          "no-import-assign": "off",
          "no-invalid-regexp": "error",
          "no-irregular-whitespace": "error",
          "no-loss-of-precision": "error",
          "no-misleading-character-class": "error",
          "no-new-native-nonconstructor": "off",
          "no-nonoctal-decimal-escape": "error",
          "no-obj-calls": "off",
          "no-prototype-builtins": "error",
          "no-redeclare": "off",
          "no-regex-spaces": "error",
          "no-self-assign": "error",
          "no-setter-return": "off",
          "no-shadow-restricted-names": "error",
          "no-sparse-arrays": "error",
          "no-this-before-super": "off",
          "no-undef": "off",
          "no-unexpected-multiline": "off",
          "no-unreachable": "off",
          "no-unsafe-finally": "error",
          "no-unsafe-negation": "off",
          "no-unsafe-optional-chaining": "error",
          "no-unused-labels": "error",
          "no-unused-private-class-members": "error",
          "no-unused-vars": "error",
          "no-useless-backreference": "error",
          "no-useless-catch": "error",
          "no-useless-escape": "error",
          "no-with": "off",
          "require-yield": "error",
          "use-isnan": "error",
          "valid-typeof": "error",
          "vue/no-arrow-functions-in-watch": "error",
          "vue/no-async-in-computed-properties": "error",
          "vue/no-computed-properties-in-data": "error",
          "vue/no-deprecated-data-object-declaration": "error",
          "vue/no-deprecated-delete-set": "error",
          "vue/no-deprecated-destroyed-lifecycle": "error",
          "vue/no-deprecated-events-api": "error",
          "vue/no-deprecated-model-definition": "error",
          "vue/no-deprecated-props-default-this": "error",
          "vue/no-deprecated-vue-config-keycodes": "error",
          "vue/no-dupe-keys": "error",
          "vue/no-export-in-script-setup": "error",
          "vue/no-expose-after-await": "error",
          "vue/no-lifecycle-after-await": "error",
          "vue/no-reserved-component-names": "off",
          "vue/no-reserved-keys": "error",
          "vue/no-reserved-props": "error",
          "vue/no-shared-component-data": "error",
          "vue/no-side-effects-in-computed-properties": "error",
          "vue/no-watch-after-await": "error",
          "vue/prefer-import-from-vue": "error",
          "vue/require-prop-type-constructor": "error",
          "vue/require-render-return": "error",
          "vue/require-slots-as-functions": "error",
          "vue/return-in-computed-property": "error",
          "vue/return-in-emits-validator": "error",
          "vue/valid-define-emits": "error",
          "vue/valid-define-options": "error",
          "vue/valid-define-props": "error",
          "vue/valid-next-tick": "error",
          "vue/component-definition-name-casing": "warn",
          "vue/prop-name-casing": "warn",
          "vue/require-default-prop": "off",
          "vue/require-prop-types": "warn",
          "vue/no-multiple-slot-args": "warn",
          "vue/no-required-prop-with-default": "warn",
          "no-var": "error",
          "prefer-const": "error",
          "prefer-rest-params": "error",
          "prefer-spread": "error",
          "no-array-constructor": "error",
          "no-unused-expressions": "error",
          "typescript/ban-ts-comment": "error",
          "typescript/no-duplicate-enum-values": "error",
          "typescript/no-empty-object-type": "error",
          "typescript/no-explicit-any": "off",
          "typescript/no-extra-non-null-assertion": "error",
          "typescript/no-misused-new": "error",
          "typescript/no-namespace": "error",
          "typescript/no-non-null-asserted-optional-chain": "error",
          "typescript/no-require-imports": "error",
          "typescript/no-this-alias": "error",
          "typescript/no-unnecessary-type-constraint": "error",
          "typescript/no-unsafe-declaration-merging": "error",
          "typescript/no-unsafe-function-type": "error",
          "typescript/no-wrapper-object-types": "error",
          "typescript/prefer-as-const": "error",
          "typescript/prefer-namespace-keyword": "error",
          "typescript/triple-slash-reference": "error",
          curly: "off",
          "unicorn/empty-brace-spaces": "off",
          "unicorn/no-nested-ternary": "off",
          "unicorn/number-literal-case": "off",
          "prettier/prettier": "off",
          "no-param-reassign": "error",
        },
        plugins: ["vue"],
        jsPlugins: ["eslint-plugin-prettier"],
        env: {
          es2026: true,
          browser: true,
          node: true,
        },
      },
    ],
    options: {},
    jsPlugins: [
      {
        name: "vite-plus",
        specifier: "vite-plus/oxlint-plugin",
      },
    ],
    rules: {
      "vite-plus/prefer-vite-plus-imports": "error",
    },
  },
  fmt: {
    printWidth: 100,
    trailingComma: "es5",
    sortPackageJson: false,
    ignorePatterns: ["tests/custom-css.css"],
    overrides: [{ files: ["**/*.vue"], options: { tabWidth: 4 } }],
  },
  root: "./assets",
  publicDir: "public",
  base: "./",
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./assets/js"),
    },
  },
  css: {
    transformer: "lightningcss",
    lightningcss: {
      drafts: { customMedia: true },
      targets: browserslistToTargets(browserslist()),
    },
  },
  build: {
    outDir: "../dist/",
    emptyOutDir: true,
    assetsInlineLimit: 1024,
    chunkSizeWarningLimit: 800, // legacy build increases file size
  },
  server: (() => {
    const frontend = Number(process.env.VITE_PORT) || 7071;
    const backend = Number(process.env.VITE_BACKEND_PORT) || 7070;
    return {
      port: frontend,
      proxy: {
        "/api": `http://localhost:${backend}`,
        "/i18n": `http://localhost:${backend}`,
        "/providerauth": `http://localhost:${backend}`,
        "/ws": { target: `ws://localhost:${backend}`, ws: true },
      },
    };
  })(),
  plugins: lazyPlugins(() => [
    legacy({
      modernPolyfills: ["es.promise.all-settled"],
    }),
    vuePlugin({
      template: {
        compilerOptions: {
          isCustomElement: (tag) => tag.startsWith("shopicon-"),
        },
      },
    }),
    visualizer({ filename: "asset-stats.html" }),
  ]),
});
