package charger

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/evcc-io/evcc/api"
)

func decorateCfos(base *CfosPowerBrain, meter func() (float64, error), energyImport func() (float64, error), phaseCurrents func() (float64, float64, float64, error), phaseSwitcher func(int) error) api.Charger {
	switch {
	case energyImport == nil && meter == nil && phaseSwitcher == nil:
		return base

	case energyImport == nil && meter != nil && phaseCurrents == nil && phaseSwitcher == nil:
		return &struct {
			*CfosPowerBrain
			api.Meter
		}{
			CfosPowerBrain: base,
			Meter: &decorateCfosMeterImpl{
				meter: meter,
			},
		}

	case energyImport != nil && meter == nil && phaseSwitcher == nil:
		return &struct {
			*CfosPowerBrain
			api.EnergyImport
		}{
			CfosPowerBrain: base,
			EnergyImport: &decorateCfosEnergyImportImpl{
				energyImport: energyImport,
			},
		}

	case energyImport != nil && meter != nil && phaseCurrents == nil && phaseSwitcher == nil:
		return &struct {
			*CfosPowerBrain
			api.EnergyImport
			api.Meter
		}{
			CfosPowerBrain: base,
			EnergyImport: &decorateCfosEnergyImportImpl{
				energyImport: energyImport,
			},
			Meter: &decorateCfosMeterImpl{
				meter: meter,
			},
		}

	case energyImport == nil && meter != nil && phaseCurrents != nil && phaseSwitcher == nil:
		return &struct {
			*CfosPowerBrain
			api.Meter
			api.PhaseCurrents
		}{
			CfosPowerBrain: base,
			Meter: &decorateCfosMeterImpl{
				meter: meter,
			},
			PhaseCurrents: &decorateCfosPhaseCurrentsImpl{
				phaseCurrents: phaseCurrents,
			},
		}

	case energyImport != nil && meter != nil && phaseCurrents != nil && phaseSwitcher == nil:
		return &struct {
			*CfosPowerBrain
			api.EnergyImport
			api.Meter
			api.PhaseCurrents
		}{
			CfosPowerBrain: base,
			EnergyImport: &decorateCfosEnergyImportImpl{
				energyImport: energyImport,
			},
			Meter: &decorateCfosMeterImpl{
				meter: meter,
			},
			PhaseCurrents: &decorateCfosPhaseCurrentsImpl{
				phaseCurrents: phaseCurrents,
			},
		}

	case energyImport == nil && meter == nil && phaseSwitcher != nil:
		return &struct {
			*CfosPowerBrain
			api.PhaseSwitcher
		}{
			CfosPowerBrain: base,
			PhaseSwitcher: &decorateCfosPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}

	case energyImport == nil && meter != nil && phaseCurrents == nil && phaseSwitcher != nil:
		return &struct {
			*CfosPowerBrain
			api.Meter
			api.PhaseSwitcher
		}{
			CfosPowerBrain: base,
			Meter: &decorateCfosMeterImpl{
				meter: meter,
			},
			PhaseSwitcher: &decorateCfosPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}

	case energyImport != nil && meter == nil && phaseSwitcher != nil:
		return &struct {
			*CfosPowerBrain
			api.EnergyImport
			api.PhaseSwitcher
		}{
			CfosPowerBrain: base,
			EnergyImport: &decorateCfosEnergyImportImpl{
				energyImport: energyImport,
			},
			PhaseSwitcher: &decorateCfosPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}

	case energyImport != nil && meter != nil && phaseCurrents == nil && phaseSwitcher != nil:
		return &struct {
			*CfosPowerBrain
			api.EnergyImport
			api.Meter
			api.PhaseSwitcher
		}{
			CfosPowerBrain: base,
			EnergyImport: &decorateCfosEnergyImportImpl{
				energyImport: energyImport,
			},
			Meter: &decorateCfosMeterImpl{
				meter: meter,
			},
			PhaseSwitcher: &decorateCfosPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}

	case energyImport == nil && meter != nil && phaseCurrents != nil && phaseSwitcher != nil:
		return &struct {
			*CfosPowerBrain
			api.Meter
			api.PhaseCurrents
			api.PhaseSwitcher
		}{
			CfosPowerBrain: base,
			Meter: &decorateCfosMeterImpl{
				meter: meter,
			},
			PhaseCurrents: &decorateCfosPhaseCurrentsImpl{
				phaseCurrents: phaseCurrents,
			},
			PhaseSwitcher: &decorateCfosPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}

	case energyImport != nil && meter != nil && phaseCurrents != nil && phaseSwitcher != nil:
		return &struct {
			*CfosPowerBrain
			api.EnergyImport
			api.Meter
			api.PhaseCurrents
			api.PhaseSwitcher
		}{
			CfosPowerBrain: base,
			EnergyImport: &decorateCfosEnergyImportImpl{
				energyImport: energyImport,
			},
			Meter: &decorateCfosMeterImpl{
				meter: meter,
			},
			PhaseCurrents: &decorateCfosPhaseCurrentsImpl{
				phaseCurrents: phaseCurrents,
			},
			PhaseSwitcher: &decorateCfosPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}
	}

	return nil
}

type decorateCfosEnergyImportImpl struct {
	energyImport func() (float64, error)
}

func (impl *decorateCfosEnergyImportImpl) EnergyImport() (float64, error) {
	return impl.energyImport()
}

type decorateCfosMeterImpl struct {
	meter func() (float64, error)
}

func (impl *decorateCfosMeterImpl) CurrentPower() (float64, error) {
	return impl.meter()
}

type decorateCfosPhaseCurrentsImpl struct {
	phaseCurrents func() (float64, float64, float64, error)
}

func (impl *decorateCfosPhaseCurrentsImpl) Currents() (float64, float64, float64, error) {
	return impl.phaseCurrents()
}

type decorateCfosPhaseSwitcherImpl struct {
	phaseSwitcher func(int) error
}

func (impl *decorateCfosPhaseSwitcherImpl) Phases1p3p(p0 int) error {
	return impl.phaseSwitcher(p0)
}
