package charger

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/evcc-io/evcc/api"
)

func decorateEm2Go(base *Em2Go, phaseSwitcher func(int) error) api.Charger {
	switch {
	case phaseSwitcher == nil:
		return base

	case phaseSwitcher != nil:
		return &struct {
			*Em2Go
			api.PhaseSwitcher
		}{
			Em2Go: base,
			PhaseSwitcher: &decorateEm2GoPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}
	}

	return nil
}

type decorateEm2GoPhaseSwitcherImpl struct {
	phaseSwitcher func(int) error
}

func (impl *decorateEm2GoPhaseSwitcherImpl) Phases1p3p(p0 int) error {
	return impl.phaseSwitcher(p0)
}
