package charger

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/evcc-io/evcc/api"
)

func decorateEtek(base *Etek, meter func() (float64, error), meterEnergy func() (float64, error), phaseVoltages func() (float64, float64, float64, error)) api.Charger {
	switch {
	case meter == nil:
		return base

	case meter != nil && meterEnergy == nil && phaseVoltages == nil:
		return &struct {
			*Etek
			api.Meter
		}{
			Etek: base,
			Meter: &decorateEtekMeterImpl{
				meter: meter,
			},
		}

	case meter != nil && meterEnergy != nil && phaseVoltages == nil:
		return &struct {
			*Etek
			api.Meter
			api.MeterEnergy
		}{
			Etek: base,
			Meter: &decorateEtekMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateEtekMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case meter != nil && meterEnergy == nil && phaseVoltages != nil:
		return &struct {
			*Etek
			api.Meter
			api.PhaseVoltages
		}{
			Etek: base,
			Meter: &decorateEtekMeterImpl{
				meter: meter,
			},
			PhaseVoltages: &decorateEtekPhaseVoltagesImpl{
				phaseVoltages: phaseVoltages,
			},
		}

	case meter != nil && meterEnergy != nil && phaseVoltages != nil:
		return &struct {
			*Etek
			api.Meter
			api.MeterEnergy
			api.PhaseVoltages
		}{
			Etek: base,
			Meter: &decorateEtekMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateEtekMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			PhaseVoltages: &decorateEtekPhaseVoltagesImpl{
				phaseVoltages: phaseVoltages,
			},
		}
	}

	return nil
}

type decorateEtekMeterImpl struct {
	meter func() (float64, error)
}

func (impl *decorateEtekMeterImpl) CurrentPower() (float64, error) {
	return impl.meter()
}

type decorateEtekMeterEnergyImpl struct {
	meterEnergy func() (float64, error)
}

func (impl *decorateEtekMeterEnergyImpl) TotalEnergy() (float64, error) {
	return impl.meterEnergy()
}

type decorateEtekPhaseVoltagesImpl struct {
	phaseVoltages func() (float64, float64, float64, error)
}

func (impl *decorateEtekPhaseVoltagesImpl) Voltages() (float64, float64, float64, error) {
	return impl.phaseVoltages()
}
