package charger

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"reflect"

	"github.com/evcc-io/evcc/api"
	"github.com/evcc-io/evcc/api/implement"
)

func decorateEVECUBE(base *EVECUBE, phaseSwitcher func(int) error, identifier func() (string, error)) api.Charger {
	caps := make(map[reflect.Type]any)

	if phaseSwitcher != nil {
		caps[reflect.TypeFor[api.PhaseSwitcher]()] = implement.PhaseSwitcher(phaseSwitcher)
	}

	if identifier != nil {
		caps[reflect.TypeFor[api.Identifier]()] = implement.Identifier(identifier)
	}

	if len(caps) == 0 {
		return base
	}

	return &decorateEVECUBECapable{EVECUBE: base, caps: caps}
}

type decorateEVECUBECapable struct {
	*EVECUBE
	caps map[reflect.Type]any
}

func (d *decorateEVECUBECapable) Capability(typ reflect.Type) (any, bool) {
	c, ok := d.caps[typ]
	if !ok && reflect.TypeOf(d).Implements(typ) {
		return d, true
	}
	return c, ok
}
