package charger

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"reflect"

	"github.com/evcc-io/evcc/api"
)

func decorateHeatpump(base *Heatpump, meter func() (float64, error), meterEnergy func() (float64, error), battery func() (float64, error), socLimiter func() (int64, error)) api.Charger {
	caps := make(map[reflect.Type]any)

	if meter != nil {
		caps[reflect.TypeFor[api.Meter]()] = &decorateHeatpumpMeterImpl{meter: meter}
	}

	if meterEnergy != nil {
		caps[reflect.TypeFor[api.MeterEnergy]()] = &decorateHeatpumpMeterEnergyImpl{meterEnergy: meterEnergy}
	}

	if battery != nil {
		caps[reflect.TypeFor[api.Battery]()] = &decorateHeatpumpBatteryImpl{battery: battery}
	}

	if socLimiter != nil {
		caps[reflect.TypeFor[api.SocLimiter]()] = &decorateHeatpumpSocLimiterImpl{socLimiter: socLimiter}
	}

	if len(caps) == 0 {
		return base
	}

	return &decorateHeatpumpCapable{Heatpump: base, caps: caps}
}

type decorateHeatpumpCapable struct {
	*Heatpump
	caps map[reflect.Type]any
}

func (d *decorateHeatpumpCapable) Capability(typ reflect.Type) (any, bool) {
	c, ok := d.caps[typ]
	if !ok && reflect.TypeOf(d).Implements(typ) {
		return d, true
	}
	return c, ok
}

type decorateHeatpumpBatteryImpl struct {
	battery func() (float64, error)
}

func (impl *decorateHeatpumpBatteryImpl) Soc() (float64, error) {
	return impl.battery()
}

type decorateHeatpumpMeterImpl struct {
	meter func() (float64, error)
}

func (impl *decorateHeatpumpMeterImpl) CurrentPower() (float64, error) {
	return impl.meter()
}

type decorateHeatpumpMeterEnergyImpl struct {
	meterEnergy func() (float64, error)
}

func (impl *decorateHeatpumpMeterEnergyImpl) TotalEnergy() (float64, error) {
	return impl.meterEnergy()
}

type decorateHeatpumpSocLimiterImpl struct {
	socLimiter func() (int64, error)
}

func (impl *decorateHeatpumpSocLimiterImpl) GetLimitSoc() (int64, error) {
	return impl.socLimiter()
}
