package charger

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/evcc-io/evcc/api"
)

func decorateHomeAssistant(base *HomeAssistant, meter func() (float64, error), meterEnergy func() (float64, error), phaseCurrents func() (float64, float64, float64, error), phaseVoltages func() (float64, float64, float64, error), phaseSwitcher func(int) error, phaseGetter func() (int, error)) api.Charger {
	switch {
	case meter == nil && phaseSwitcher == nil:
		return base

	case meter != nil && meterEnergy == nil && phaseCurrents == nil && phaseSwitcher == nil && phaseVoltages == nil:
		return &struct {
			*HomeAssistant
			api.Meter
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
		}

	case meter != nil && meterEnergy != nil && phaseCurrents == nil && phaseSwitcher == nil && phaseVoltages == nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.MeterEnergy
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateHomeAssistantMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case meter != nil && meterEnergy == nil && phaseCurrents != nil && phaseSwitcher == nil && phaseVoltages == nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.PhaseCurrents
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			PhaseCurrents: &decorateHomeAssistantPhaseCurrentsImpl{
				phaseCurrents: phaseCurrents,
			},
		}

	case meter != nil && meterEnergy != nil && phaseCurrents != nil && phaseSwitcher == nil && phaseVoltages == nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.MeterEnergy
			api.PhaseCurrents
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateHomeAssistantMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			PhaseCurrents: &decorateHomeAssistantPhaseCurrentsImpl{
				phaseCurrents: phaseCurrents,
			},
		}

	case meter != nil && meterEnergy == nil && phaseCurrents == nil && phaseSwitcher == nil && phaseVoltages != nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.PhaseVoltages
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			PhaseVoltages: &decorateHomeAssistantPhaseVoltagesImpl{
				phaseVoltages: phaseVoltages,
			},
		}

	case meter != nil && meterEnergy != nil && phaseCurrents == nil && phaseSwitcher == nil && phaseVoltages != nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.MeterEnergy
			api.PhaseVoltages
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateHomeAssistantMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			PhaseVoltages: &decorateHomeAssistantPhaseVoltagesImpl{
				phaseVoltages: phaseVoltages,
			},
		}

	case meter != nil && meterEnergy == nil && phaseCurrents != nil && phaseSwitcher == nil && phaseVoltages != nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.PhaseCurrents
			api.PhaseVoltages
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			PhaseCurrents: &decorateHomeAssistantPhaseCurrentsImpl{
				phaseCurrents: phaseCurrents,
			},
			PhaseVoltages: &decorateHomeAssistantPhaseVoltagesImpl{
				phaseVoltages: phaseVoltages,
			},
		}

	case meter != nil && meterEnergy != nil && phaseCurrents != nil && phaseSwitcher == nil && phaseVoltages != nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.MeterEnergy
			api.PhaseCurrents
			api.PhaseVoltages
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateHomeAssistantMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			PhaseCurrents: &decorateHomeAssistantPhaseCurrentsImpl{
				phaseCurrents: phaseCurrents,
			},
			PhaseVoltages: &decorateHomeAssistantPhaseVoltagesImpl{
				phaseVoltages: phaseVoltages,
			},
		}

	case meter == nil && phaseGetter == nil && phaseSwitcher != nil:
		return &struct {
			*HomeAssistant
			api.PhaseSwitcher
		}{
			HomeAssistant: base,
			PhaseSwitcher: &decorateHomeAssistantPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}

	case meter != nil && meterEnergy == nil && phaseCurrents == nil && phaseGetter == nil && phaseSwitcher != nil && phaseVoltages == nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.PhaseSwitcher
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			PhaseSwitcher: &decorateHomeAssistantPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}

	case meter != nil && meterEnergy != nil && phaseCurrents == nil && phaseGetter == nil && phaseSwitcher != nil && phaseVoltages == nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.MeterEnergy
			api.PhaseSwitcher
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateHomeAssistantMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			PhaseSwitcher: &decorateHomeAssistantPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}

	case meter != nil && meterEnergy == nil && phaseCurrents != nil && phaseGetter == nil && phaseSwitcher != nil && phaseVoltages == nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.PhaseCurrents
			api.PhaseSwitcher
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			PhaseCurrents: &decorateHomeAssistantPhaseCurrentsImpl{
				phaseCurrents: phaseCurrents,
			},
			PhaseSwitcher: &decorateHomeAssistantPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}

	case meter != nil && meterEnergy != nil && phaseCurrents != nil && phaseGetter == nil && phaseSwitcher != nil && phaseVoltages == nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.MeterEnergy
			api.PhaseCurrents
			api.PhaseSwitcher
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateHomeAssistantMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			PhaseCurrents: &decorateHomeAssistantPhaseCurrentsImpl{
				phaseCurrents: phaseCurrents,
			},
			PhaseSwitcher: &decorateHomeAssistantPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}

	case meter != nil && meterEnergy == nil && phaseCurrents == nil && phaseGetter == nil && phaseSwitcher != nil && phaseVoltages != nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.PhaseSwitcher
			api.PhaseVoltages
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			PhaseSwitcher: &decorateHomeAssistantPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
			PhaseVoltages: &decorateHomeAssistantPhaseVoltagesImpl{
				phaseVoltages: phaseVoltages,
			},
		}

	case meter != nil && meterEnergy != nil && phaseCurrents == nil && phaseGetter == nil && phaseSwitcher != nil && phaseVoltages != nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.MeterEnergy
			api.PhaseSwitcher
			api.PhaseVoltages
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateHomeAssistantMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			PhaseSwitcher: &decorateHomeAssistantPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
			PhaseVoltages: &decorateHomeAssistantPhaseVoltagesImpl{
				phaseVoltages: phaseVoltages,
			},
		}

	case meter != nil && meterEnergy == nil && phaseCurrents != nil && phaseGetter == nil && phaseSwitcher != nil && phaseVoltages != nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.PhaseCurrents
			api.PhaseSwitcher
			api.PhaseVoltages
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			PhaseCurrents: &decorateHomeAssistantPhaseCurrentsImpl{
				phaseCurrents: phaseCurrents,
			},
			PhaseSwitcher: &decorateHomeAssistantPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
			PhaseVoltages: &decorateHomeAssistantPhaseVoltagesImpl{
				phaseVoltages: phaseVoltages,
			},
		}

	case meter != nil && meterEnergy != nil && phaseCurrents != nil && phaseGetter == nil && phaseSwitcher != nil && phaseVoltages != nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.MeterEnergy
			api.PhaseCurrents
			api.PhaseSwitcher
			api.PhaseVoltages
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateHomeAssistantMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			PhaseCurrents: &decorateHomeAssistantPhaseCurrentsImpl{
				phaseCurrents: phaseCurrents,
			},
			PhaseSwitcher: &decorateHomeAssistantPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
			PhaseVoltages: &decorateHomeAssistantPhaseVoltagesImpl{
				phaseVoltages: phaseVoltages,
			},
		}

	case meter == nil && phaseGetter != nil && phaseSwitcher != nil:
		return &struct {
			*HomeAssistant
			api.PhaseGetter
			api.PhaseSwitcher
		}{
			HomeAssistant: base,
			PhaseGetter: &decorateHomeAssistantPhaseGetterImpl{
				phaseGetter: phaseGetter,
			},
			PhaseSwitcher: &decorateHomeAssistantPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}

	case meter != nil && meterEnergy == nil && phaseCurrents == nil && phaseGetter != nil && phaseSwitcher != nil && phaseVoltages == nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.PhaseGetter
			api.PhaseSwitcher
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			PhaseGetter: &decorateHomeAssistantPhaseGetterImpl{
				phaseGetter: phaseGetter,
			},
			PhaseSwitcher: &decorateHomeAssistantPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}

	case meter != nil && meterEnergy != nil && phaseCurrents == nil && phaseGetter != nil && phaseSwitcher != nil && phaseVoltages == nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.MeterEnergy
			api.PhaseGetter
			api.PhaseSwitcher
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateHomeAssistantMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			PhaseGetter: &decorateHomeAssistantPhaseGetterImpl{
				phaseGetter: phaseGetter,
			},
			PhaseSwitcher: &decorateHomeAssistantPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}

	case meter != nil && meterEnergy == nil && phaseCurrents != nil && phaseGetter != nil && phaseSwitcher != nil && phaseVoltages == nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.PhaseCurrents
			api.PhaseGetter
			api.PhaseSwitcher
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			PhaseCurrents: &decorateHomeAssistantPhaseCurrentsImpl{
				phaseCurrents: phaseCurrents,
			},
			PhaseGetter: &decorateHomeAssistantPhaseGetterImpl{
				phaseGetter: phaseGetter,
			},
			PhaseSwitcher: &decorateHomeAssistantPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}

	case meter != nil && meterEnergy != nil && phaseCurrents != nil && phaseGetter != nil && phaseSwitcher != nil && phaseVoltages == nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.MeterEnergy
			api.PhaseCurrents
			api.PhaseGetter
			api.PhaseSwitcher
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateHomeAssistantMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			PhaseCurrents: &decorateHomeAssistantPhaseCurrentsImpl{
				phaseCurrents: phaseCurrents,
			},
			PhaseGetter: &decorateHomeAssistantPhaseGetterImpl{
				phaseGetter: phaseGetter,
			},
			PhaseSwitcher: &decorateHomeAssistantPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}

	case meter != nil && meterEnergy == nil && phaseCurrents == nil && phaseGetter != nil && phaseSwitcher != nil && phaseVoltages != nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.PhaseGetter
			api.PhaseSwitcher
			api.PhaseVoltages
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			PhaseGetter: &decorateHomeAssistantPhaseGetterImpl{
				phaseGetter: phaseGetter,
			},
			PhaseSwitcher: &decorateHomeAssistantPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
			PhaseVoltages: &decorateHomeAssistantPhaseVoltagesImpl{
				phaseVoltages: phaseVoltages,
			},
		}

	case meter != nil && meterEnergy != nil && phaseCurrents == nil && phaseGetter != nil && phaseSwitcher != nil && phaseVoltages != nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.MeterEnergy
			api.PhaseGetter
			api.PhaseSwitcher
			api.PhaseVoltages
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateHomeAssistantMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			PhaseGetter: &decorateHomeAssistantPhaseGetterImpl{
				phaseGetter: phaseGetter,
			},
			PhaseSwitcher: &decorateHomeAssistantPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
			PhaseVoltages: &decorateHomeAssistantPhaseVoltagesImpl{
				phaseVoltages: phaseVoltages,
			},
		}

	case meter != nil && meterEnergy == nil && phaseCurrents != nil && phaseGetter != nil && phaseSwitcher != nil && phaseVoltages != nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.PhaseCurrents
			api.PhaseGetter
			api.PhaseSwitcher
			api.PhaseVoltages
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			PhaseCurrents: &decorateHomeAssistantPhaseCurrentsImpl{
				phaseCurrents: phaseCurrents,
			},
			PhaseGetter: &decorateHomeAssistantPhaseGetterImpl{
				phaseGetter: phaseGetter,
			},
			PhaseSwitcher: &decorateHomeAssistantPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
			PhaseVoltages: &decorateHomeAssistantPhaseVoltagesImpl{
				phaseVoltages: phaseVoltages,
			},
		}

	case meter != nil && meterEnergy != nil && phaseCurrents != nil && phaseGetter != nil && phaseSwitcher != nil && phaseVoltages != nil:
		return &struct {
			*HomeAssistant
			api.Meter
			api.MeterEnergy
			api.PhaseCurrents
			api.PhaseGetter
			api.PhaseSwitcher
			api.PhaseVoltages
		}{
			HomeAssistant: base,
			Meter: &decorateHomeAssistantMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateHomeAssistantMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			PhaseCurrents: &decorateHomeAssistantPhaseCurrentsImpl{
				phaseCurrents: phaseCurrents,
			},
			PhaseGetter: &decorateHomeAssistantPhaseGetterImpl{
				phaseGetter: phaseGetter,
			},
			PhaseSwitcher: &decorateHomeAssistantPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
			PhaseVoltages: &decorateHomeAssistantPhaseVoltagesImpl{
				phaseVoltages: phaseVoltages,
			},
		}
	}

	return nil
}

type decorateHomeAssistantMeterImpl struct {
	meter func() (float64, error)
}

func (impl *decorateHomeAssistantMeterImpl) CurrentPower() (float64, error) {
	return impl.meter()
}

type decorateHomeAssistantMeterEnergyImpl struct {
	meterEnergy func() (float64, error)
}

func (impl *decorateHomeAssistantMeterEnergyImpl) TotalEnergy() (float64, error) {
	return impl.meterEnergy()
}

type decorateHomeAssistantPhaseCurrentsImpl struct {
	phaseCurrents func() (float64, float64, float64, error)
}

func (impl *decorateHomeAssistantPhaseCurrentsImpl) Currents() (float64, float64, float64, error) {
	return impl.phaseCurrents()
}

type decorateHomeAssistantPhaseGetterImpl struct {
	phaseGetter func() (int, error)
}

func (impl *decorateHomeAssistantPhaseGetterImpl) GetPhases() (int, error) {
	return impl.phaseGetter()
}

type decorateHomeAssistantPhaseSwitcherImpl struct {
	phaseSwitcher func(int) error
}

func (impl *decorateHomeAssistantPhaseSwitcherImpl) Phases1p3p(p0 int) error {
	return impl.phaseSwitcher(p0)
}

type decorateHomeAssistantPhaseVoltagesImpl struct {
	phaseVoltages func() (float64, float64, float64, error)
}

func (impl *decorateHomeAssistantPhaseVoltagesImpl) Voltages() (float64, float64, float64, error) {
	return impl.phaseVoltages()
}
