package charger

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"reflect"

	"github.com/evcc-io/evcc/api"
)

func decorateHomeAssistant(base *HomeAssistant, meter func() (float64, error), meterEnergy func() (float64, error), phaseCurrents func() (float64, float64, float64, error), phaseVoltages func() (float64, float64, float64, error), phaseSwitcher func(int) error, phaseGetter func() (int, error)) api.Charger {
	caps := make(map[reflect.Type]any)

	if meter != nil {
		caps[reflect.TypeFor[api.Meter]()] = &decorateHomeAssistantMeterImpl{meter: meter}
	}

	if meterEnergy != nil {
		caps[reflect.TypeFor[api.MeterEnergy]()] = &decorateHomeAssistantMeterEnergyImpl{meterEnergy: meterEnergy}
	}

	if phaseCurrents != nil {
		caps[reflect.TypeFor[api.PhaseCurrents]()] = &decorateHomeAssistantPhaseCurrentsImpl{phaseCurrents: phaseCurrents}
	}

	if phaseVoltages != nil {
		caps[reflect.TypeFor[api.PhaseVoltages]()] = &decorateHomeAssistantPhaseVoltagesImpl{phaseVoltages: phaseVoltages}
	}

	if phaseSwitcher != nil {
		caps[reflect.TypeFor[api.PhaseSwitcher]()] = &decorateHomeAssistantPhaseSwitcherImpl{phaseSwitcher: phaseSwitcher}
	}

	if phaseGetter != nil {
		caps[reflect.TypeFor[api.PhaseGetter]()] = &decorateHomeAssistantPhaseGetterImpl{phaseGetter: phaseGetter}
	}

	if len(caps) == 0 {
		return base
	}

	return &decorateHomeAssistantCapable{HomeAssistant: base, caps: caps}
}

type decorateHomeAssistantCapable struct {
	*HomeAssistant
	caps map[reflect.Type]any
}

func (d *decorateHomeAssistantCapable) Capability(typ reflect.Type) (any, bool) {
	c, ok := d.caps[typ]
	return c, ok
}

type decorateHomeAssistantMeterImpl struct {
	meter func() (float64, error)
}

func (impl *decorateHomeAssistantMeterImpl) CurrentPower() (float64, error) {
	return impl.meter()
}

type decorateHomeAssistantMeterEnergyImpl struct {
	meterEnergy func() (float64, error)
}

func (impl *decorateHomeAssistantMeterEnergyImpl) TotalEnergy() (float64, error) {
	return impl.meterEnergy()
}

type decorateHomeAssistantPhaseCurrentsImpl struct {
	phaseCurrents func() (float64, float64, float64, error)
}

func (impl *decorateHomeAssistantPhaseCurrentsImpl) Currents() (float64, float64, float64, error) {
	return impl.phaseCurrents()
}

type decorateHomeAssistantPhaseGetterImpl struct {
	phaseGetter func() (int, error)
}

func (impl *decorateHomeAssistantPhaseGetterImpl) GetPhases() (int, error) {
	return impl.phaseGetter()
}

type decorateHomeAssistantPhaseSwitcherImpl struct {
	phaseSwitcher func(int) error
}

func (impl *decorateHomeAssistantPhaseSwitcherImpl) Phases1p3p(p0 int) error {
	return impl.phaseSwitcher(p0)
}

type decorateHomeAssistantPhaseVoltagesImpl struct {
	phaseVoltages func() (float64, float64, float64, error)
}

func (impl *decorateHomeAssistantPhaseVoltagesImpl) Voltages() (float64, float64, float64, error) {
	return impl.phaseVoltages()
}
