package charger

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"reflect"

	"github.com/evcc-io/evcc/api"
)

func decorateKebaUdp(base *KebaUdp, meter func() (float64, error), meterEnergy func() (float64, error), phaseCurrents func() (float64, float64, float64, error)) api.Charger {
	caps := make(map[reflect.Type]any)

	if meter != nil {
		caps[reflect.TypeFor[api.Meter]()] = &decorateKebaUdpMeterImpl{meter: meter}
	}

	if meterEnergy != nil {
		caps[reflect.TypeFor[api.MeterEnergy]()] = &decorateKebaUdpMeterEnergyImpl{meterEnergy: meterEnergy}
	}

	if phaseCurrents != nil {
		caps[reflect.TypeFor[api.PhaseCurrents]()] = &decorateKebaUdpPhaseCurrentsImpl{phaseCurrents: phaseCurrents}
	}

	if len(caps) == 0 {
		return base
	}

	return &decorateKebaUdpCapable{KebaUdp: base, caps: caps}
}

type decorateKebaUdpCapable struct {
	*KebaUdp
	caps map[reflect.Type]any
}

func (d *decorateKebaUdpCapable) Capability(typ reflect.Type) (any, bool) {
	c, ok := d.caps[typ]
	if !ok && reflect.TypeOf(d).Implements(typ) {
		return d, true
	}
	return c, ok
}

type decorateKebaUdpMeterImpl struct {
	meter func() (float64, error)
}

func (impl *decorateKebaUdpMeterImpl) CurrentPower() (float64, error) {
	return impl.meter()
}

type decorateKebaUdpMeterEnergyImpl struct {
	meterEnergy func() (float64, error)
}

func (impl *decorateKebaUdpMeterEnergyImpl) TotalEnergy() (float64, error) {
	return impl.meterEnergy()
}

type decorateKebaUdpPhaseCurrentsImpl struct {
	phaseCurrents func() (float64, float64, float64, error)
}

func (impl *decorateKebaUdpPhaseCurrentsImpl) Currents() (float64, float64, float64, error) {
	return impl.phaseCurrents()
}
