package charger

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"reflect"

	"github.com/evcc-io/evcc/api"
	"github.com/evcc-io/evcc/api/implement"
)

func decorateKeba(base *Keba, meter func() (float64, error), meterEnergy func() (float64, error), phaseCurrents func() (float64, float64, float64, error), identifier func() (string, error), statusReasoner func() (api.Reason, error), phaseSwitcher func(int) error, phaseGetter func() (int, error)) api.Charger {
	caps := make(map[reflect.Type]any)

	if meter != nil {
		caps[reflect.TypeFor[api.Meter]()] = implement.Meter(meter)
	}

	if meterEnergy != nil {
		caps[reflect.TypeFor[api.MeterEnergy]()] = implement.MeterEnergy(meterEnergy)
	}

	if phaseCurrents != nil {
		caps[reflect.TypeFor[api.PhaseCurrents]()] = implement.PhaseCurrents(phaseCurrents)
	}

	if identifier != nil {
		caps[reflect.TypeFor[api.Identifier]()] = implement.Identifier(identifier)
	}

	if statusReasoner != nil {
		caps[reflect.TypeFor[api.StatusReasoner]()] = implement.StatusReasoner(statusReasoner)
	}

	if phaseSwitcher != nil {
		caps[reflect.TypeFor[api.PhaseSwitcher]()] = implement.PhaseSwitcher(phaseSwitcher)
	}

	if phaseGetter != nil {
		caps[reflect.TypeFor[api.PhaseGetter]()] = implement.PhaseGetter(phaseGetter)
	}

	if len(caps) == 0 {
		return base
	}

	return &decorateKebaCapable{Keba: base, caps: caps}
}

type decorateKebaCapable struct {
	*Keba
	caps map[reflect.Type]any
}

func (d *decorateKebaCapable) Capability(typ reflect.Type) (any, bool) {
	c, ok := d.caps[typ]
	if !ok && reflect.TypeOf(d).Implements(typ) {
		return d, true
	}
	return c, ok
}
