package charger

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"reflect"

	"github.com/evcc-io/evcc/api"
	"github.com/evcc-io/evcc/api/implement"
)

func decorateNRGKickGen2(base *NRGKickGen2, phaseSwitcher func(int) error) api.Charger {
	caps := make(map[reflect.Type]any)

	if phaseSwitcher != nil {
		caps[reflect.TypeFor[api.PhaseSwitcher]()] = implement.PhaseSwitcher(phaseSwitcher)
	}

	if len(caps) == 0 {
		return base
	}

	return &decorateNRGKickGen2Capable{NRGKickGen2: base, caps: caps}
}

type decorateNRGKickGen2Capable struct {
	*NRGKickGen2
	caps map[reflect.Type]any
}

func (d *decorateNRGKickGen2Capable) Capability(typ reflect.Type) (any, bool) {
	c, ok := d.caps[typ]
	if !ok && reflect.TypeOf(d).Implements(typ) {
		return d, true
	}
	return c, ok
}
