package charger

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"reflect"

	"github.com/evcc-io/evcc/api"
)

func decorateSmartEVSE3(base *SmartEVSE3, meter func() (float64, error), meterEnergy func() (float64, error), phaseCurrents func() (float64, float64, float64, error), phaseSwitcher func(int) error, phaseGetter func() (int, error)) api.Charger {
	caps := make(map[reflect.Type]any)

	if meter != nil {
		caps[reflect.TypeFor[api.Meter]()] = &decorateSmartEVSE3MeterImpl{meter: meter}
	}

	if meterEnergy != nil {
		caps[reflect.TypeFor[api.MeterEnergy]()] = &decorateSmartEVSE3MeterEnergyImpl{meterEnergy: meterEnergy}
	}

	if phaseCurrents != nil {
		caps[reflect.TypeFor[api.PhaseCurrents]()] = &decorateSmartEVSE3PhaseCurrentsImpl{phaseCurrents: phaseCurrents}
	}

	if phaseSwitcher != nil {
		caps[reflect.TypeFor[api.PhaseSwitcher]()] = &decorateSmartEVSE3PhaseSwitcherImpl{phaseSwitcher: phaseSwitcher}
	}

	if phaseGetter != nil {
		caps[reflect.TypeFor[api.PhaseGetter]()] = &decorateSmartEVSE3PhaseGetterImpl{phaseGetter: phaseGetter}
	}

	if len(caps) == 0 {
		return base
	}

	return &decorateSmartEVSE3Capable{SmartEVSE3: base, caps: caps}
}

type decorateSmartEVSE3Capable struct {
	*SmartEVSE3
	caps map[reflect.Type]any
}

func (d *decorateSmartEVSE3Capable) Capability(typ reflect.Type) (any, bool) {
	c, ok := d.caps[typ]
	return c, ok
}

type decorateSmartEVSE3MeterImpl struct {
	meter func() (float64, error)
}

func (impl *decorateSmartEVSE3MeterImpl) CurrentPower() (float64, error) {
	return impl.meter()
}

type decorateSmartEVSE3MeterEnergyImpl struct {
	meterEnergy func() (float64, error)
}

func (impl *decorateSmartEVSE3MeterEnergyImpl) TotalEnergy() (float64, error) {
	return impl.meterEnergy()
}

type decorateSmartEVSE3PhaseCurrentsImpl struct {
	phaseCurrents func() (float64, float64, float64, error)
}

func (impl *decorateSmartEVSE3PhaseCurrentsImpl) Currents() (float64, float64, float64, error) {
	return impl.phaseCurrents()
}

type decorateSmartEVSE3PhaseGetterImpl struct {
	phaseGetter func() (int, error)
}

func (impl *decorateSmartEVSE3PhaseGetterImpl) GetPhases() (int, error) {
	return impl.phaseGetter()
}

type decorateSmartEVSE3PhaseSwitcherImpl struct {
	phaseSwitcher func(int) error
}

func (impl *decorateSmartEVSE3PhaseSwitcherImpl) Phases1p3p(p0 int) error {
	return impl.phaseSwitcher(p0)
}
