package charger

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/evcc-io/evcc/api"
)

func decorateVoltie(base *Voltie, meter func() (float64, error), meterEnergy func() (float64, error), phaseCurrents func() (float64, float64, float64, error)) api.Charger {
	switch {
	case meter == nil:
		return base

	case meter != nil && meterEnergy == nil && phaseCurrents == nil:
		return &struct {
			*Voltie
			api.Meter
		}{
			Voltie: base,
			Meter: &decorateVoltieMeterImpl{
				meter: meter,
			},
		}

	case meter != nil && meterEnergy != nil && phaseCurrents == nil:
		return &struct {
			*Voltie
			api.Meter
			api.MeterEnergy
		}{
			Voltie: base,
			Meter: &decorateVoltieMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateVoltieMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case meter != nil && meterEnergy == nil && phaseCurrents != nil:
		return &struct {
			*Voltie
			api.Meter
			api.PhaseCurrents
		}{
			Voltie: base,
			Meter: &decorateVoltieMeterImpl{
				meter: meter,
			},
			PhaseCurrents: &decorateVoltiePhaseCurrentsImpl{
				phaseCurrents: phaseCurrents,
			},
		}

	case meter != nil && meterEnergy != nil && phaseCurrents != nil:
		return &struct {
			*Voltie
			api.Meter
			api.MeterEnergy
			api.PhaseCurrents
		}{
			Voltie: base,
			Meter: &decorateVoltieMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateVoltieMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
			PhaseCurrents: &decorateVoltiePhaseCurrentsImpl{
				phaseCurrents: phaseCurrents,
			},
		}
	}

	return nil
}

type decorateVoltieMeterImpl struct {
	meter func() (float64, error)
}

func (impl *decorateVoltieMeterImpl) CurrentPower() (float64, error) {
	return impl.meter()
}

type decorateVoltieMeterEnergyImpl struct {
	meterEnergy func() (float64, error)
}

func (impl *decorateVoltieMeterEnergyImpl) TotalEnergy() (float64, error) {
	return impl.meterEnergy()
}

type decorateVoltiePhaseCurrentsImpl struct {
	phaseCurrents func() (float64, float64, float64, error)
}

func (impl *decorateVoltiePhaseCurrentsImpl) Currents() (float64, float64, float64, error) {
	return impl.phaseCurrents()
}
