// Code generated by "enumer -type ObservationID"; DO NOT EDIT.

package easee

import (
	"fmt"
	"strings"
)

const _ObservationIDName = "SELF_TEST_RESULTSELF_TEST_DETAILSEASEE_LINK_COMMAND_RESPONSEEASEE_LINK_DATA_RECEIVEDSITE_ID_NUMERICSITE_STRUCTURESOFTWARE_RELEASEDEVICE_MODEMETER_TYPEMETER_IDOBIS_LIST_IDENTIFIERGRID_TYPENUM_PHASESCURRENT_L1CURRENT_L2CURRENT_L3VOLTAGE_N_L1VOLTAGE_N_L2VOLTAGE_N_L3VOLTAGE_L1_L2VOLTAGE_L1_L3VOLTAGE_L2_L3ACTIVE_POWER_IMPORTACTIVE_POWER_EXPORTREACTIVE_POWER_IMPORTREACTIVE_POWER_EXPORTMAX_POWER_IMPORTCUMULATIVE_ACTIVE_POWER_IMPORTCUMULATIVE_ACTIVE_POWER_EXPORTCUMULATIVE_REACTIVE_POWER_IMPORTCUMULATIVE_REACTIVE_POWER_EXPORTCLOCK_AND_DATE_METERRSSISSIDMASTER_BACK_PLATE_IDEQUALIZER_IDSITE_AND_CIRCUIT_STRUCTURENETWORK_SIGNAL_RSSIMETER_COMMUNICATION_CONFIGDEFAULT_LEVELAVAILABLE_CURRENT_P1AVAILABLE_CURRENT_P2AVAILABLE_CURRENT_P3RADIO_ACCESS_TECHNOLOGYPHASE_RELAY_STATUS_P1PHASE_RELAY_STATUS_P2PHASE_RELAY_STATUS_P3SECURITY_OR_ENCRYPTION_STATUSOPERATING_MODEAMP_CLAMP_STATUSCONNECTED_TO_CLOUDCLOUD_DISCONNECT_REASON"
const _ObservationIDLowerName = "self_test_resultself_test_detailseasee_link_command_responseeasee_link_data_receivedsite_id_numericsite_structuresoftware_releasedevice_modemeter_typemeter_idobis_list_identifiergrid_typenum_phasescurrent_l1current_l2current_l3voltage_n_l1voltage_n_l2voltage_n_l3voltage_l1_l2voltage_l1_l3voltage_l2_l3active_power_importactive_power_exportreactive_power_importreactive_power_exportmax_power_importcumulative_active_power_importcumulative_active_power_exportcumulative_reactive_power_importcumulative_reactive_power_exportclock_and_date_meterrssissidmaster_back_plate_idequalizer_idsite_and_circuit_structurenetwork_signal_rssimeter_communication_configdefault_levelavailable_current_p1available_current_p2available_current_p3radio_access_technologyphase_relay_status_p1phase_relay_status_p2phase_relay_status_p3security_or_encryption_statusoperating_modeamp_clamp_statusconnected_to_cloudcloud_disconnect_reason"

var _ObservationIDMap = map[ObservationID]string{
	1:   _ObservationIDName[0:16],
	2:   _ObservationIDName[16:33],
	13:  _ObservationIDName[33:60],
	14:  _ObservationIDName[60:84],
	19:  _ObservationIDName[84:99],
	20:  _ObservationIDName[99:113],
	21:  _ObservationIDName[113:129],
	23:  _ObservationIDName[129:140],
	25:  _ObservationIDName[140:150],
	26:  _ObservationIDName[150:158],
	27:  _ObservationIDName[158:178],
	29:  _ObservationIDName[178:187],
	30:  _ObservationIDName[187:197],
	31:  _ObservationIDName[197:207],
	32:  _ObservationIDName[207:217],
	33:  _ObservationIDName[217:227],
	34:  _ObservationIDName[227:239],
	35:  _ObservationIDName[239:251],
	36:  _ObservationIDName[251:263],
	37:  _ObservationIDName[263:276],
	38:  _ObservationIDName[276:289],
	39:  _ObservationIDName[289:302],
	40:  _ObservationIDName[302:321],
	41:  _ObservationIDName[321:340],
	42:  _ObservationIDName[340:361],
	43:  _ObservationIDName[361:382],
	44:  _ObservationIDName[382:398],
	45:  _ObservationIDName[398:428],
	46:  _ObservationIDName[428:458],
	47:  _ObservationIDName[458:490],
	48:  _ObservationIDName[490:522],
	49:  _ObservationIDName[522:542],
	50:  _ObservationIDName[542:546],
	51:  _ObservationIDName[546:550],
	55:  _ObservationIDName[550:570],
	56:  _ObservationIDName[570:582],
	57:  _ObservationIDName[582:608],
	70:  _ObservationIDName[608:627],
	85:  _ObservationIDName[627:653],
	86:  _ObservationIDName[653:666],
	87:  _ObservationIDName[666:686],
	88:  _ObservationIDName[686:706],
	89:  _ObservationIDName[706:726],
	100: _ObservationIDName[726:749],
	105: _ObservationIDName[749:770],
	106: _ObservationIDName[770:791],
	107: _ObservationIDName[791:812],
	111: _ObservationIDName[812:841],
	115: _ObservationIDName[841:855],
	120: _ObservationIDName[855:871],
	250: _ObservationIDName[871:889],
	251: _ObservationIDName[889:912],
}

func (i ObservationID) String() string {
	if str, ok := _ObservationIDMap[i]; ok {
		return str
	}
	return fmt.Sprintf("ObservationID(%d)", i)
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ObservationIDNoOp() {
	var x [1]struct{}
	_ = x[SELF_TEST_RESULT-(1)]
	_ = x[SELF_TEST_DETAILS-(2)]
	_ = x[EASEE_LINK_COMMAND_RESPONSE-(13)]
	_ = x[EASEE_LINK_DATA_RECEIVED-(14)]
	_ = x[SITE_ID_NUMERIC-(19)]
	_ = x[SITE_STRUCTURE-(20)]
	_ = x[SOFTWARE_RELEASE-(21)]
	_ = x[DEVICE_MODE-(23)]
	_ = x[METER_TYPE-(25)]
	_ = x[METER_ID-(26)]
	_ = x[OBIS_LIST_IDENTIFIER-(27)]
	_ = x[GRID_TYPE-(29)]
	_ = x[NUM_PHASES-(30)]
	_ = x[CURRENT_L1-(31)]
	_ = x[CURRENT_L2-(32)]
	_ = x[CURRENT_L3-(33)]
	_ = x[VOLTAGE_N_L1-(34)]
	_ = x[VOLTAGE_N_L2-(35)]
	_ = x[VOLTAGE_N_L3-(36)]
	_ = x[VOLTAGE_L1_L2-(37)]
	_ = x[VOLTAGE_L1_L3-(38)]
	_ = x[VOLTAGE_L2_L3-(39)]
	_ = x[ACTIVE_POWER_IMPORT-(40)]
	_ = x[ACTIVE_POWER_EXPORT-(41)]
	_ = x[REACTIVE_POWER_IMPORT-(42)]
	_ = x[REACTIVE_POWER_EXPORT-(43)]
	_ = x[MAX_POWER_IMPORT-(44)]
	_ = x[CUMULATIVE_ACTIVE_POWER_IMPORT-(45)]
	_ = x[CUMULATIVE_ACTIVE_POWER_EXPORT-(46)]
	_ = x[CUMULATIVE_REACTIVE_POWER_IMPORT-(47)]
	_ = x[CUMULATIVE_REACTIVE_POWER_EXPORT-(48)]
	_ = x[CLOCK_AND_DATE_METER-(49)]
	_ = x[RSSI-(50)]
	_ = x[SSID-(51)]
	_ = x[MASTER_BACK_PLATE_ID-(55)]
	_ = x[EQUALIZER_ID-(56)]
	_ = x[SITE_AND_CIRCUIT_STRUCTURE-(57)]
	_ = x[NETWORK_SIGNAL_RSSI-(70)]
	_ = x[METER_COMMUNICATION_CONFIG-(85)]
	_ = x[DEFAULT_LEVEL-(86)]
	_ = x[AVAILABLE_CURRENT_P1-(87)]
	_ = x[AVAILABLE_CURRENT_P2-(88)]
	_ = x[AVAILABLE_CURRENT_P3-(89)]
	_ = x[RADIO_ACCESS_TECHNOLOGY-(100)]
	_ = x[PHASE_RELAY_STATUS_P1-(105)]
	_ = x[PHASE_RELAY_STATUS_P2-(106)]
	_ = x[PHASE_RELAY_STATUS_P3-(107)]
	_ = x[SECURITY_OR_ENCRYPTION_STATUS-(111)]
	_ = x[OPERATING_MODE-(115)]
	_ = x[AMP_CLAMP_STATUS-(120)]
	_ = x[CONNECTED_TO_CLOUD-(250)]
	_ = x[CLOUD_DISCONNECT_REASON-(251)]
}

var _ObservationIDValues = []ObservationID{SELF_TEST_RESULT, SELF_TEST_DETAILS, EASEE_LINK_COMMAND_RESPONSE, EASEE_LINK_DATA_RECEIVED, SITE_ID_NUMERIC, SITE_STRUCTURE, SOFTWARE_RELEASE, DEVICE_MODE, METER_TYPE, METER_ID, OBIS_LIST_IDENTIFIER, GRID_TYPE, NUM_PHASES, CURRENT_L1, CURRENT_L2, CURRENT_L3, VOLTAGE_N_L1, VOLTAGE_N_L2, VOLTAGE_N_L3, VOLTAGE_L1_L2, VOLTAGE_L1_L3, VOLTAGE_L2_L3, ACTIVE_POWER_IMPORT, ACTIVE_POWER_EXPORT, REACTIVE_POWER_IMPORT, REACTIVE_POWER_EXPORT, MAX_POWER_IMPORT, CUMULATIVE_ACTIVE_POWER_IMPORT, CUMULATIVE_ACTIVE_POWER_EXPORT, CUMULATIVE_REACTIVE_POWER_IMPORT, CUMULATIVE_REACTIVE_POWER_EXPORT, CLOCK_AND_DATE_METER, RSSI, SSID, MASTER_BACK_PLATE_ID, EQUALIZER_ID, SITE_AND_CIRCUIT_STRUCTURE, NETWORK_SIGNAL_RSSI, METER_COMMUNICATION_CONFIG, DEFAULT_LEVEL, AVAILABLE_CURRENT_P1, AVAILABLE_CURRENT_P2, AVAILABLE_CURRENT_P3, RADIO_ACCESS_TECHNOLOGY, PHASE_RELAY_STATUS_P1, PHASE_RELAY_STATUS_P2, PHASE_RELAY_STATUS_P3, SECURITY_OR_ENCRYPTION_STATUS, OPERATING_MODE, AMP_CLAMP_STATUS, CONNECTED_TO_CLOUD, CLOUD_DISCONNECT_REASON}

var _ObservationIDNameToValueMap = map[string]ObservationID{
	_ObservationIDName[0:16]:         SELF_TEST_RESULT,
	_ObservationIDLowerName[0:16]:    SELF_TEST_RESULT,
	_ObservationIDName[16:33]:        SELF_TEST_DETAILS,
	_ObservationIDLowerName[16:33]:   SELF_TEST_DETAILS,
	_ObservationIDName[33:60]:        EASEE_LINK_COMMAND_RESPONSE,
	_ObservationIDLowerName[33:60]:   EASEE_LINK_COMMAND_RESPONSE,
	_ObservationIDName[60:84]:        EASEE_LINK_DATA_RECEIVED,
	_ObservationIDLowerName[60:84]:   EASEE_LINK_DATA_RECEIVED,
	_ObservationIDName[84:99]:        SITE_ID_NUMERIC,
	_ObservationIDLowerName[84:99]:   SITE_ID_NUMERIC,
	_ObservationIDName[99:113]:       SITE_STRUCTURE,
	_ObservationIDLowerName[99:113]:  SITE_STRUCTURE,
	_ObservationIDName[113:129]:      SOFTWARE_RELEASE,
	_ObservationIDLowerName[113:129]: SOFTWARE_RELEASE,
	_ObservationIDName[129:140]:      DEVICE_MODE,
	_ObservationIDLowerName[129:140]: DEVICE_MODE,
	_ObservationIDName[140:150]:      METER_TYPE,
	_ObservationIDLowerName[140:150]: METER_TYPE,
	_ObservationIDName[150:158]:      METER_ID,
	_ObservationIDLowerName[150:158]: METER_ID,
	_ObservationIDName[158:178]:      OBIS_LIST_IDENTIFIER,
	_ObservationIDLowerName[158:178]: OBIS_LIST_IDENTIFIER,
	_ObservationIDName[178:187]:      GRID_TYPE,
	_ObservationIDLowerName[178:187]: GRID_TYPE,
	_ObservationIDName[187:197]:      NUM_PHASES,
	_ObservationIDLowerName[187:197]: NUM_PHASES,
	_ObservationIDName[197:207]:      CURRENT_L1,
	_ObservationIDLowerName[197:207]: CURRENT_L1,
	_ObservationIDName[207:217]:      CURRENT_L2,
	_ObservationIDLowerName[207:217]: CURRENT_L2,
	_ObservationIDName[217:227]:      CURRENT_L3,
	_ObservationIDLowerName[217:227]: CURRENT_L3,
	_ObservationIDName[227:239]:      VOLTAGE_N_L1,
	_ObservationIDLowerName[227:239]: VOLTAGE_N_L1,
	_ObservationIDName[239:251]:      VOLTAGE_N_L2,
	_ObservationIDLowerName[239:251]: VOLTAGE_N_L2,
	_ObservationIDName[251:263]:      VOLTAGE_N_L3,
	_ObservationIDLowerName[251:263]: VOLTAGE_N_L3,
	_ObservationIDName[263:276]:      VOLTAGE_L1_L2,
	_ObservationIDLowerName[263:276]: VOLTAGE_L1_L2,
	_ObservationIDName[276:289]:      VOLTAGE_L1_L3,
	_ObservationIDLowerName[276:289]: VOLTAGE_L1_L3,
	_ObservationIDName[289:302]:      VOLTAGE_L2_L3,
	_ObservationIDLowerName[289:302]: VOLTAGE_L2_L3,
	_ObservationIDName[302:321]:      ACTIVE_POWER_IMPORT,
	_ObservationIDLowerName[302:321]: ACTIVE_POWER_IMPORT,
	_ObservationIDName[321:340]:      ACTIVE_POWER_EXPORT,
	_ObservationIDLowerName[321:340]: ACTIVE_POWER_EXPORT,
	_ObservationIDName[340:361]:      REACTIVE_POWER_IMPORT,
	_ObservationIDLowerName[340:361]: REACTIVE_POWER_IMPORT,
	_ObservationIDName[361:382]:      REACTIVE_POWER_EXPORT,
	_ObservationIDLowerName[361:382]: REACTIVE_POWER_EXPORT,
	_ObservationIDName[382:398]:      MAX_POWER_IMPORT,
	_ObservationIDLowerName[382:398]: MAX_POWER_IMPORT,
	_ObservationIDName[398:428]:      CUMULATIVE_ACTIVE_POWER_IMPORT,
	_ObservationIDLowerName[398:428]: CUMULATIVE_ACTIVE_POWER_IMPORT,
	_ObservationIDName[428:458]:      CUMULATIVE_ACTIVE_POWER_EXPORT,
	_ObservationIDLowerName[428:458]: CUMULATIVE_ACTIVE_POWER_EXPORT,
	_ObservationIDName[458:490]:      CUMULATIVE_REACTIVE_POWER_IMPORT,
	_ObservationIDLowerName[458:490]: CUMULATIVE_REACTIVE_POWER_IMPORT,
	_ObservationIDName[490:522]:      CUMULATIVE_REACTIVE_POWER_EXPORT,
	_ObservationIDLowerName[490:522]: CUMULATIVE_REACTIVE_POWER_EXPORT,
	_ObservationIDName[522:542]:      CLOCK_AND_DATE_METER,
	_ObservationIDLowerName[522:542]: CLOCK_AND_DATE_METER,
	_ObservationIDName[542:546]:      RSSI,
	_ObservationIDLowerName[542:546]: RSSI,
	_ObservationIDName[546:550]:      SSID,
	_ObservationIDLowerName[546:550]: SSID,
	_ObservationIDName[550:570]:      MASTER_BACK_PLATE_ID,
	_ObservationIDLowerName[550:570]: MASTER_BACK_PLATE_ID,
	_ObservationIDName[570:582]:      EQUALIZER_ID,
	_ObservationIDLowerName[570:582]: EQUALIZER_ID,
	_ObservationIDName[582:608]:      SITE_AND_CIRCUIT_STRUCTURE,
	_ObservationIDLowerName[582:608]: SITE_AND_CIRCUIT_STRUCTURE,
	_ObservationIDName[608:627]:      NETWORK_SIGNAL_RSSI,
	_ObservationIDLowerName[608:627]: NETWORK_SIGNAL_RSSI,
	_ObservationIDName[627:653]:      METER_COMMUNICATION_CONFIG,
	_ObservationIDLowerName[627:653]: METER_COMMUNICATION_CONFIG,
	_ObservationIDName[653:666]:      DEFAULT_LEVEL,
	_ObservationIDLowerName[653:666]: DEFAULT_LEVEL,
	_ObservationIDName[666:686]:      AVAILABLE_CURRENT_P1,
	_ObservationIDLowerName[666:686]: AVAILABLE_CURRENT_P1,
	_ObservationIDName[686:706]:      AVAILABLE_CURRENT_P2,
	_ObservationIDLowerName[686:706]: AVAILABLE_CURRENT_P2,
	_ObservationIDName[706:726]:      AVAILABLE_CURRENT_P3,
	_ObservationIDLowerName[706:726]: AVAILABLE_CURRENT_P3,
	_ObservationIDName[726:749]:      RADIO_ACCESS_TECHNOLOGY,
	_ObservationIDLowerName[726:749]: RADIO_ACCESS_TECHNOLOGY,
	_ObservationIDName[749:770]:      PHASE_RELAY_STATUS_P1,
	_ObservationIDLowerName[749:770]: PHASE_RELAY_STATUS_P1,
	_ObservationIDName[770:791]:      PHASE_RELAY_STATUS_P2,
	_ObservationIDLowerName[770:791]: PHASE_RELAY_STATUS_P2,
	_ObservationIDName[791:812]:      PHASE_RELAY_STATUS_P3,
	_ObservationIDLowerName[791:812]: PHASE_RELAY_STATUS_P3,
	_ObservationIDName[812:841]:      SECURITY_OR_ENCRYPTION_STATUS,
	_ObservationIDLowerName[812:841]: SECURITY_OR_ENCRYPTION_STATUS,
	_ObservationIDName[841:855]:      OPERATING_MODE,
	_ObservationIDLowerName[841:855]: OPERATING_MODE,
	_ObservationIDName[855:871]:      AMP_CLAMP_STATUS,
	_ObservationIDLowerName[855:871]: AMP_CLAMP_STATUS,
	_ObservationIDName[871:889]:      CONNECTED_TO_CLOUD,
	_ObservationIDLowerName[871:889]: CONNECTED_TO_CLOUD,
	_ObservationIDName[889:912]:      CLOUD_DISCONNECT_REASON,
	_ObservationIDLowerName[889:912]: CLOUD_DISCONNECT_REASON,
}

var _ObservationIDNames = []string{
	_ObservationIDName[0:16],
	_ObservationIDName[16:33],
	_ObservationIDName[33:60],
	_ObservationIDName[60:84],
	_ObservationIDName[84:99],
	_ObservationIDName[99:113],
	_ObservationIDName[113:129],
	_ObservationIDName[129:140],
	_ObservationIDName[140:150],
	_ObservationIDName[150:158],
	_ObservationIDName[158:178],
	_ObservationIDName[178:187],
	_ObservationIDName[187:197],
	_ObservationIDName[197:207],
	_ObservationIDName[207:217],
	_ObservationIDName[217:227],
	_ObservationIDName[227:239],
	_ObservationIDName[239:251],
	_ObservationIDName[251:263],
	_ObservationIDName[263:276],
	_ObservationIDName[276:289],
	_ObservationIDName[289:302],
	_ObservationIDName[302:321],
	_ObservationIDName[321:340],
	_ObservationIDName[340:361],
	_ObservationIDName[361:382],
	_ObservationIDName[382:398],
	_ObservationIDName[398:428],
	_ObservationIDName[428:458],
	_ObservationIDName[458:490],
	_ObservationIDName[490:522],
	_ObservationIDName[522:542],
	_ObservationIDName[542:546],
	_ObservationIDName[546:550],
	_ObservationIDName[550:570],
	_ObservationIDName[570:582],
	_ObservationIDName[582:608],
	_ObservationIDName[608:627],
	_ObservationIDName[627:653],
	_ObservationIDName[653:666],
	_ObservationIDName[666:686],
	_ObservationIDName[686:706],
	_ObservationIDName[706:726],
	_ObservationIDName[726:749],
	_ObservationIDName[749:770],
	_ObservationIDName[770:791],
	_ObservationIDName[791:812],
	_ObservationIDName[812:841],
	_ObservationIDName[841:855],
	_ObservationIDName[855:871],
	_ObservationIDName[871:889],
	_ObservationIDName[889:912],
}

// ObservationIDString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ObservationIDString(s string) (ObservationID, error) {
	if val, ok := _ObservationIDNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ObservationIDNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ObservationID values", s)
}

// ObservationIDValues returns all values of the enum
func ObservationIDValues() []ObservationID {
	return _ObservationIDValues
}

// ObservationIDStrings returns a slice of all String values of the enum
func ObservationIDStrings() []string {
	strs := make([]string, len(_ObservationIDNames))
	copy(strs, _ObservationIDNames)
	return strs
}

// IsAObservationID returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ObservationID) IsAObservationID() bool {
	_, ok := _ObservationIDMap[i]
	return ok
}
