package main

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/evcc-io/evcc/api"
)

func decorateTest(base api.Charger, energyImport func() (float64, error), phaseSwitcher func(int) error, phaseGetter func() (int, error)) api.Charger {
	switch {
	case energyImport == nil && phaseSwitcher == nil:
		return base

	case energyImport != nil && phaseSwitcher == nil:
		return &struct {
			api.Charger
			api.EnergyImport
		}{
			Charger: base,
			EnergyImport: &decorateTestEnergyImportImpl{
				energyImport: energyImport,
			},
		}

	case energyImport == nil && phaseGetter == nil && phaseSwitcher != nil:
		return &struct {
			api.Charger
			api.PhaseSwitcher
		}{
			Charger: base,
			PhaseSwitcher: &decorateTestPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}

	case energyImport != nil && phaseGetter == nil && phaseSwitcher != nil:
		return &struct {
			api.Charger
			api.EnergyImport
			api.PhaseSwitcher
		}{
			Charger: base,
			EnergyImport: &decorateTestEnergyImportImpl{
				energyImport: energyImport,
			},
			PhaseSwitcher: &decorateTestPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}

	case energyImport == nil && phaseGetter != nil && phaseSwitcher != nil:
		return &struct {
			api.Charger
			api.PhaseGetter
			api.PhaseSwitcher
		}{
			Charger: base,
			PhaseGetter: &decorateTestPhaseGetterImpl{
				phaseGetter: phaseGetter,
			},
			PhaseSwitcher: &decorateTestPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}

	case energyImport != nil && phaseGetter != nil && phaseSwitcher != nil:
		return &struct {
			api.Charger
			api.EnergyImport
			api.PhaseGetter
			api.PhaseSwitcher
		}{
			Charger: base,
			EnergyImport: &decorateTestEnergyImportImpl{
				energyImport: energyImport,
			},
			PhaseGetter: &decorateTestPhaseGetterImpl{
				phaseGetter: phaseGetter,
			},
			PhaseSwitcher: &decorateTestPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}
	}

	return nil
}

type decorateTestEnergyImportImpl struct {
	energyImport func() (float64, error)
}

func (impl *decorateTestEnergyImportImpl) EnergyImport() (float64, error) {
	return impl.energyImport()
}

type decorateTestPhaseGetterImpl struct {
	phaseGetter func() (int, error)
}

func (impl *decorateTestPhaseGetterImpl) GetPhases() (int, error) {
	return impl.phaseGetter()
}

type decorateTestPhaseSwitcherImpl struct {
	phaseSwitcher func(int) error
}

func (impl *decorateTestPhaseSwitcherImpl) Phases1p3p(p0 int) error {
	return impl.phaseSwitcher(p0)
}
