maxcurrent: 63 # 63A main circuit breaker (optional)
maxpower: 30000 # 30kW (optional)


## dynamic limits via plugins (optional, override the static values above)

#getmaxcurrent:
#  source: const
#  value: 32
#getmaxpower:
#  source: js
#  script: 20000

#timeout: 1m # treat as overloaded if meter values are older than this (optional)
