## required attributes [type: sgready-boost]

charger: # configuration of a switch controlling the sg-ready port
  type: template
  template: shelly # example shelly
  host: 192.168.0.101 #

## optional attributes (read-only)

#temp: # current temperature (°C)
#  source: const
#  value: 42
#limittemp: # temperature limit (°C) configured in device
#  source: const
#  value: 84
