blank_issues_enabled: false
contact_links:
  - name: Need help?
    url: https://github.com/evcc-io/evcc/discussions/categories/need-help
    about: GitHub community discussions is a good place to ask questions.
