// Code generated by "enumer -type suggestionAction -trimprefix action -transform=lower"; DO NOT EDIT.

package core

import (
	"fmt"
	"strings"
)

const _suggestionActionName = "stopcharge"

var _suggestionActionIndex = [...]uint8{0, 4, 10}

const _suggestionActionLowerName = "stopcharge"

func (i suggestionAction) String() string {
	if i < 0 || i >= suggestionAction(len(_suggestionActionIndex)-1) {
		return fmt.Sprintf("suggestionAction(%d)", i)
	}
	return _suggestionActionName[_suggestionActionIndex[i]:_suggestionActionIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _suggestionActionNoOp() {
	var x [1]struct{}
	_ = x[actionStop-(0)]
	_ = x[actionCharge-(1)]
}

var _suggestionActionValues = []suggestionAction{actionStop, actionCharge}

var _suggestionActionNameToValueMap = map[string]suggestionAction{
	_suggestionActionName[0:4]:       actionStop,
	_suggestionActionLowerName[0:4]:  actionStop,
	_suggestionActionName[4:10]:      actionCharge,
	_suggestionActionLowerName[4:10]: actionCharge,
}

var _suggestionActionNames = []string{
	_suggestionActionName[0:4],
	_suggestionActionName[4:10],
}

// suggestionActionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func suggestionActionString(s string) (suggestionAction, error) {
	if val, ok := _suggestionActionNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _suggestionActionNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to suggestionAction values", s)
}

// suggestionActionValues returns all values of the enum
func suggestionActionValues() []suggestionAction {
	return _suggestionActionValues
}

// suggestionActionStrings returns a slice of all String values of the enum
func suggestionActionStrings() []string {
	strs := make([]string, len(_suggestionActionNames))
	copy(strs, _suggestionActionNames)
	return strs
}

// IsAsuggestionAction returns "true" if the value is listed in the enum definition. "false" otherwise
func (i suggestionAction) IsAsuggestionAction() bool {
	for _, v := range _suggestionActionValues {
		if i == v {
			return true
		}
	}
	return false
}
