// Code generated by "enumer -type Key"; DO NOT EDIT.

package plugin

import (
	"fmt"
	"strings"
)

const _KeyName = "PowerEnergy"

var _KeyIndex = [...]uint8{0, 5, 11}

const _KeyLowerName = "powerenergy"

func (i Key) String() string {
	i -= 1
	if i < 0 || i >= Key(len(_KeyIndex)-1) {
		return fmt.Sprintf("Key(%d)", i+1)
	}
	return _KeyName[_KeyIndex[i]:_KeyIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _KeyNoOp() {
	var x [1]struct{}
	_ = x[Power-(1)]
	_ = x[Energy-(2)]
}

var _KeyValues = []Key{Power, Energy}

var _KeyNameToValueMap = map[string]Key{
	_KeyName[0:5]:       Power,
	_KeyLowerName[0:5]:  Power,
	_KeyName[5:11]:      Energy,
	_KeyLowerName[5:11]: Energy,
}

var _KeyNames = []string{
	_KeyName[0:5],
	_KeyName[5:11],
}

// KeyString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func KeyString(s string) (Key, error) {
	if val, ok := _KeyNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _KeyNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Key values", s)
}

// KeyValues returns all values of the enum
func KeyValues() []Key {
	return _KeyValues
}

// KeyStrings returns a slice of all String values of the enum
func KeyStrings() []string {
	strs := make([]string, len(_KeyNames))
	copy(strs, _KeyNames)
	return strs
}

// IsAKey returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Key) IsAKey() bool {
	for _, v := range _KeyValues {
		if i == v {
			return true
		}
	}
	return false
}
