// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.35.1
// source: proto/devicehost.proto

// protoc proto/devicehost.proto --go_out=. --go-grpc_out=.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceHost_Types_FullMethodName = "/devicehost.DeviceHost/Types"
	DeviceHost_New_FullMethodName   = "/devicehost.DeviceHost/New"
	DeviceHost_Call_FullMethodName  = "/devicehost.DeviceHost/Call"
)

// DeviceHostClient is the client API for DeviceHost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DeviceHost is a host exposing device types that evcc configures and instantiates
type DeviceHostClient interface {
	// Types returns the device types this host can instantiate
	Types(ctx context.Context, in *TypesRequest, opts ...grpc.CallOption) (*TypesReply, error)
	// New instantiates a device type from configuration properties
	New(ctx context.Context, in *NewRequest, opts ...grpc.CallOption) (*NewReply, error)
	// Call invokes a capability method on an instantiated device
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallReply, error)
}

type deviceHostClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceHostClient(cc grpc.ClientConnInterface) DeviceHostClient {
	return &deviceHostClient{cc}
}

func (c *deviceHostClient) Types(ctx context.Context, in *TypesRequest, opts ...grpc.CallOption) (*TypesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypesReply)
	err := c.cc.Invoke(ctx, DeviceHost_Types_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceHostClient) New(ctx context.Context, in *NewRequest, opts ...grpc.CallOption) (*NewReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewReply)
	err := c.cc.Invoke(ctx, DeviceHost_New_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceHostClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallReply)
	err := c.cc.Invoke(ctx, DeviceHost_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceHostServer is the server API for DeviceHost service.
// All implementations must embed UnimplementedDeviceHostServer
// for forward compatibility.
//
// DeviceHost is a host exposing device types that evcc configures and instantiates
type DeviceHostServer interface {
	// Types returns the device types this host can instantiate
	Types(context.Context, *TypesRequest) (*TypesReply, error)
	// New instantiates a device type from configuration properties
	New(context.Context, *NewRequest) (*NewReply, error)
	// Call invokes a capability method on an instantiated device
	Call(context.Context, *CallRequest) (*CallReply, error)
	mustEmbedUnimplementedDeviceHostServer()
}

// UnimplementedDeviceHostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceHostServer struct{}

func (UnimplementedDeviceHostServer) Types(context.Context, *TypesRequest) (*TypesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Types not implemented")
}
func (UnimplementedDeviceHostServer) New(context.Context, *NewRequest) (*NewReply, error) {
	return nil, status.Error(codes.Unimplemented, "method New not implemented")
}
func (UnimplementedDeviceHostServer) Call(context.Context, *CallRequest) (*CallReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedDeviceHostServer) mustEmbedUnimplementedDeviceHostServer() {}
func (UnimplementedDeviceHostServer) testEmbeddedByValue()                    {}

// UnsafeDeviceHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceHostServer will
// result in compilation errors.
type UnsafeDeviceHostServer interface {
	mustEmbedUnimplementedDeviceHostServer()
}

func RegisterDeviceHostServer(s grpc.ServiceRegistrar, srv DeviceHostServer) {
	// If the following call panics, it indicates UnimplementedDeviceHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceHost_ServiceDesc, srv)
}

func _DeviceHost_Types_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceHostServer).Types(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceHost_Types_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceHostServer).Types(ctx, req.(*TypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceHost_New_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceHostServer).New(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceHost_New_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceHostServer).New(ctx, req.(*NewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceHost_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceHostServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceHost_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceHostServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceHost_ServiceDesc is the grpc.ServiceDesc for DeviceHost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceHost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devicehost.DeviceHost",
	HandlerType: (*DeviceHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Types",
			Handler:    _DeviceHost_Types_Handler,
		},
		{
			MethodName: "New",
			Handler:    _DeviceHost_New_Handler,
		},
		{
			MethodName: "Call",
			Handler:    _DeviceHost_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/devicehost.proto",
}
