// Code generated by redact_gen.go; DO NOT EDIT.

package util

// generatedRedactParams contains params marked as mask=true or private=true
var generatedRedactParams = []string{
	"accessToken",
	"ain",
	"apiKey",
	"key",
	"lat",
	"lon",
	"mac",
	"password",
	"pin",
	"refreshToken",
	"serial",
	"serial_number",
	"ski",
	"token",
	"uri",
	"url",
	"user",
	"uuid",
	"vin",
	"zip",
}
