//go:build ignore

package main

import (
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/evcc-io/evcc/util/templates"
)

func main() {
	templates.ConfigDefaults.Load()

	// Collect all sensitive params from templates (includes defaults)
	var params []string
	for _, class := range templates.ClassValues() {
		for _, tmpl := range templates.ByClass(class) {
			for _, p := range tmpl.Params {
				if p.IsMasked() || p.IsPrivate() {
					params = append(params, p.Name)
				}
			}
		}
	}

	// Sort and deduplicate (case-insensitive)
	slices.SortFunc(params, func(a, b string) int {
		return strings.Compare(strings.ToLower(a), strings.ToLower(b))
	})

	// Remove case-insensitive duplicates (keep first occurrence)
	params = slices.CompactFunc(params, func(a, b string) bool {
		return strings.EqualFold(a, b)
	})

	// Generate
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by redact_gen.go; DO NOT EDIT.\n\npackage util\n\n")
	fmt.Fprintf(&b, "// generatedRedactParams contains params marked as mask=true or private=true\n")
	fmt.Fprintf(&b, "var generatedRedactParams = []string{\n")
	for _, p := range params {
		fmt.Fprintf(&b, "\t%q,\n", p)
	}
	fmt.Fprintf(&b, "}\n")

	if err := os.WriteFile("redact_list.go", []byte(b.String()), 0644); err != nil {
		panic(err)
	}

	fmt.Printf("Generated redact_list.go with %d params\n", len(params))
}