package keys

const (
	Interval           = "interval"
	PasswordConfigured = "passwordConfigured"
	Sponsor            = "sponsor"
	SponsorToken       = "sponsorToken"
	Network            = "network"
	Mqtt               = "mqtt"
	Influx             = "influx"
	EEBus              = "eebus"
	Hems               = "hems"
	Shm                = "shm"
	Messaging          = "messaging"
	ModbusProxy        = "modbusproxy"
	Tariffs            = "tariffs"
	Version            = "version"
	Config             = "config"
	Database           = "database"
	Fatal              = "fatal"
	Startup            = "startup"
	Plant              = "plant"
	Telemetry          = "telemetry"
	DemoMode           = "demoMode"
	AuthDisabled       = "authDisabled"
	AuthProviders      = "authProviders"
)
