package keys

// TODO use

const (
	Aux                   = "aux"
	AuxPower              = "auxPower"
	Battery               = "battery"
	BatteryCapacity       = "batteryCapacity"
	BatteryConfigured     = "batteryConfigured"
	BatteryEnergy         = "batteryEnergy"
	BatteryPower          = "batteryPower"
	BatterySoc            = "batterySoc"
	BufferSoc             = "bufferSoc"
	BufferStartSoc        = "bufferStartSoc"
	Currency              = "currency"
	GreenShareHome        = "greenShareHome"
	GreenShareLoadpoints  = "greenShareLoadpoints"
	GridConfigured        = "gridConfigured"
	GridCurrents          = "gridCurrents"
	GridEnergy            = "gridEnergy"
	GridPowers            = "gridPowers"
	HomePower             = "homePower"
	PrioritySoc           = "prioritySoc"
	Pv                    = "pv"
	PvConfigured          = "pvConfigured"
	PvEnergy              = "pvEnergy"
	PvPower               = "pvPower"
	ResidualPower         = "residualPower"
	SiteTitle             = "siteTitle"
	SmartCostActive       = "smartCostActive"
	SmartCostLimit        = "smartCostLimit"
	SmartCostType         = "smartCostType"
	TariffCo2             = "tariffCo2"
	TariffCo2Home         = "tariffCo2Home"
	TariffCo2Loadpoints   = "tariffCo2Loadpoin"
	TariffFeedIn          = "tariffFeedIn"
	TariffGrid            = "tariffGrid"
	TariffPriceHome       = "tariffPriceHome"
	TariffPriceLoadpoints = "tariffPriceLoadpoints"
	Vehicles              = "vehicles"
)
