// Code generated by "enumer -type Feature -text"; DO NOT EDIT.

package api

import (
	"fmt"
	"strings"
)

const _FeatureName = "CoarseCurrentIntegratedDeviceSwitchDeviceHeatingScaleLoadByTemperatureForecastContinuousAverageCacheableOfflineRetryableStreamingWelcomeChargeClimaterDisabledAutodetectDisabledWakeUpDisabled"

var _FeatureIndex = [...]uint8{0, 13, 29, 41, 48, 78, 88, 95, 104, 111, 120, 129, 142, 158, 176, 190}

const _FeatureLowerName = "coarsecurrentintegrateddeviceswitchdeviceheatingscaleloadbytemperatureforecastcontinuousaveragecacheableofflineretryablestreamingwelcomechargeclimaterdisabledautodetectdisabledwakeupdisabled"

func (i Feature) String() string {
	i -= 1
	if i < 0 || i >= Feature(len(_FeatureIndex)-1) {
		return fmt.Sprintf("Feature(%d)", i+1)
	}
	return _FeatureName[_FeatureIndex[i]:_FeatureIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FeatureNoOp() {
	var x [1]struct{}
	_ = x[CoarseCurrent-(1)]
	_ = x[IntegratedDevice-(2)]
	_ = x[SwitchDevice-(3)]
	_ = x[Heating-(4)]
	_ = x[ScaleLoadByTemperatureForecast-(5)]
	_ = x[Continuous-(6)]
	_ = x[Average-(7)]
	_ = x[Cacheable-(8)]
	_ = x[Offline-(9)]
	_ = x[Retryable-(10)]
	_ = x[Streaming-(11)]
	_ = x[WelcomeCharge-(12)]
	_ = x[ClimaterDisabled-(13)]
	_ = x[AutodetectDisabled-(14)]
	_ = x[WakeUpDisabled-(15)]
}

var _FeatureValues = []Feature{CoarseCurrent, IntegratedDevice, SwitchDevice, Heating, ScaleLoadByTemperatureForecast, Continuous, Average, Cacheable, Offline, Retryable, Streaming, WelcomeCharge, ClimaterDisabled, AutodetectDisabled, WakeUpDisabled}

var _FeatureNameToValueMap = map[string]Feature{
	_FeatureName[0:13]:         CoarseCurrent,
	_FeatureLowerName[0:13]:    CoarseCurrent,
	_FeatureName[13:29]:        IntegratedDevice,
	_FeatureLowerName[13:29]:   IntegratedDevice,
	_FeatureName[29:41]:        SwitchDevice,
	_FeatureLowerName[29:41]:   SwitchDevice,
	_FeatureName[41:48]:        Heating,
	_FeatureLowerName[41:48]:   Heating,
	_FeatureName[48:78]:        ScaleLoadByTemperatureForecast,
	_FeatureLowerName[48:78]:   ScaleLoadByTemperatureForecast,
	_FeatureName[78:88]:        Continuous,
	_FeatureLowerName[78:88]:   Continuous,
	_FeatureName[88:95]:        Average,
	_FeatureLowerName[88:95]:   Average,
	_FeatureName[95:104]:       Cacheable,
	_FeatureLowerName[95:104]:  Cacheable,
	_FeatureName[104:111]:      Offline,
	_FeatureLowerName[104:111]: Offline,
	_FeatureName[111:120]:      Retryable,
	_FeatureLowerName[111:120]: Retryable,
	_FeatureName[120:129]:      Streaming,
	_FeatureLowerName[120:129]: Streaming,
	_FeatureName[129:142]:      WelcomeCharge,
	_FeatureLowerName[129:142]: WelcomeCharge,
	_FeatureName[142:158]:      ClimaterDisabled,
	_FeatureLowerName[142:158]: ClimaterDisabled,
	_FeatureName[158:176]:      AutodetectDisabled,
	_FeatureLowerName[158:176]: AutodetectDisabled,
	_FeatureName[176:190]:      WakeUpDisabled,
	_FeatureLowerName[176:190]: WakeUpDisabled,
}

var _FeatureNames = []string{
	_FeatureName[0:13],
	_FeatureName[13:29],
	_FeatureName[29:41],
	_FeatureName[41:48],
	_FeatureName[48:78],
	_FeatureName[78:88],
	_FeatureName[88:95],
	_FeatureName[95:104],
	_FeatureName[104:111],
	_FeatureName[111:120],
	_FeatureName[120:129],
	_FeatureName[129:142],
	_FeatureName[142:158],
	_FeatureName[158:176],
	_FeatureName[176:190],
}

// FeatureString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FeatureString(s string) (Feature, error) {
	if val, ok := _FeatureNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FeatureNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Feature values", s)
}

// FeatureValues returns all values of the enum
func FeatureValues() []Feature {
	return _FeatureValues
}

// FeatureStrings returns a slice of all String values of the enum
func FeatureStrings() []string {
	strs := make([]string, len(_FeatureNames))
	copy(strs, _FeatureNames)
	return strs
}

// IsAFeature returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Feature) IsAFeature() bool {
	for _, v := range _FeatureValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for Feature
func (i Feature) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Feature
func (i *Feature) UnmarshalText(text []byte) error {
	var err error
	*i, err = FeatureString(string(text))
	return err
}
