name: Release

permissions:
  contents: read

on:
  push:
    tags:
      - "*"

jobs:
  call-build-workflow:
    if: startsWith(github.ref, 'refs/tags')
    uses: jeffborg/evcc/.github/workflows/default.yml@master
    permissions:
      contents: read
      actions: write

  release:
    name: Create GitHub Release
    needs:
      - docker
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

  docker:
    name: Publish Docker :release
    needs:
      - call-build-workflow
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Login
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4

      - name: Meta
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6
        with:
          images: |
            ghcr.io/jeffborg/evcc

      - name: Publish
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v6
          push: true
          build-args: |
            RELEASE=1
          tags: ${{ steps.meta.outputs.tags }}
