name: "Stale issue handler"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  issue_comment:
    types: [created]

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        id: stale
        with:
          days-before-stale: 7
          days-before-close: 5
          exempt-issue-labels: "pinned,security,backlog,bug"
          exempt-pr-labels: "pinned,security,backlog,bug"
