package vehicle

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"reflect"

	"github.com/evcc-io/evcc/api"
	"github.com/evcc-io/evcc/api/implement"
)

func decorateTronity(base *Tronity, chargeState func() (api.ChargeStatus, error), vehicleOdometer func() (float64, error), chargeController func(bool) error) api.Vehicle {
	caps := make(map[reflect.Type]any)

	if chargeState != nil {
		caps[reflect.TypeFor[api.ChargeState]()] = implement.ChargeState(chargeState)
	}

	if vehicleOdometer != nil {
		caps[reflect.TypeFor[api.VehicleOdometer]()] = implement.VehicleOdometer(vehicleOdometer)
	}

	if chargeController != nil {
		caps[reflect.TypeFor[api.ChargeController]()] = implement.ChargeController(chargeController)
	}

	if len(caps) == 0 {
		return base
	}

	return &decorateTronityCapable{Tronity: base, caps: caps}
}

type decorateTronityCapable struct {
	*Tronity
	caps map[reflect.Type]any
}

func (d *decorateTronityCapable) Capability(typ reflect.Type) (any, bool) {
	c, ok := d.caps[typ]
	if !ok && reflect.TypeOf(d).Implements(typ) {
		return d, true
	}
	return c, ok
}
