package vehicle

// Code generated by github.com/andig/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/andig/evcc/api"
)

func decorateVehicle(base api.Vehicle, status func() (api.ChargeStatus, error)) api.Vehicle {
	switch {
	case status == nil:
		return base

	case status != nil:
		return &struct {
			api.Vehicle
			api.Status
		}{
			Vehicle: base,
			Status: &decorateVehicleStatusImpl{
				status: status,
			},
		}
	}

	return nil
}

type decorateVehicleStatusImpl struct {
	status func() (api.ChargeStatus, error)
}

func (impl *decorateVehicleStatusImpl) Status() (api.ChargeStatus, error) {
	return impl.status()
}
